### ISSUE TITLE
感谢大佬

### ISSUE THREAD

**Issue by gujiwuqing** [imzbf/md-editor-rt#10]
大佬 我感觉你的这个蛮好用的  虽然感觉有点像借鉴一个  然后感觉这文档  基于react的话 要不然 咱文档也写个react的例子

**Comment by gujiwuqing** [comment]
谢谢大佬 白嫖党不胜感激

**Comment by imzbf** [comment]
> 大佬 我感觉你的这个蛮好用的 虽然感觉有点像借鉴一个 然后感觉这文档 基于react的话 要不然 咱文档也写个react的例子

react的例子是指？rt版本的文档就是使用react写的呢，包括展示编辑器和展示文档功能呢

**Comment by gujiwuqing** [comment]
https://imzbf.github.io/md-editor-rt
![image](https://user-images.githubusercontent.com/44566835/148866753-c97930cb-81b8-4700-a372-301f5c7ec1b5.png)
在这里 看差了 应该看文档的
