### ISSUE TITLE
版本3和版本4 在Safari浏览器上 直接白屏了

### ISSUE THREAD

**Issue by RainScorpio** [imzbf/md-editor-rt#100]
### 描述这个Bug

浏览器:
* Safari浏览器 版本号 14.1.2 
*  谷歌浏览器 版本号  83.0.4103.97

谷歌浏览器版本86以上没有发现这个问题, 正常显示

问题:
使用版本3 或者 版本4 的话, 页面直接白屏, 版本2的没有问题
报错消息如下:
Uncaught SyntaxError: Unexpected token '('

![企业微信截图_16922683208244](https://github.com/imzbf/md-editor-rt/assets/13704570/3cae959c-9e50-47ec-b2eb-2b6c79985bf3)

![21cbac82-fccc-4178-ae9a-c46ad6e160d0](https://github.com/imzbf/md-editor-rt/assets/13704570/d0f22d27-319a-4e4e-95ac-203332946282)

是依赖的这个lru-cache报的错误
![image](https://github.com/imzbf/md-editor-rt/assets/13704570/369f3e56-c341-4df5-98e2-59e6be7ebf04)

### 版本号

node版本是 v16.14.2
用的是umi的框架, 版本是3.5.35

**Comment by imzbf** [comment]
抱歉，这边还原不了你描述的问题
<img width="722" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/37092006/8be799fd-8def-4c1e-a204-3fc813468830">

方便的话，提供一下你这边能发现问题的一个最简的环境

**Comment by RainScorpio** [comment]
我们用的是react 17.x
估计是打包生成的代码不同吧

**Comment by RainScorpio** [comment]
有什么打包的规则吗? 我查到的原因就是语法问题, 一些浏览器不支持#开头的私有变量

**Comment by imzbf** [comment]
> 有什么打包的规则吗? 我查到的原因就是语法问题, 一些浏览器不支持#开头的私有变量

Safar14.1开始支持，可能你的环境需要`@babel/plugin-proposal-private-methods`这个

**Comment by RainScorpio** [comment]
好的, 我试试, 谢谢
