### ISSUE TITLE
NextJs中，MdCatalog点击不生效

### ISSUE THREAD

**Issue by BenjaminCCG** [imzbf/md-editor-rt#101]
### Describe the issue

function About({initData}:{initData:Article}) {
  const [id] = useState('preview-only');
  const [articleDetail] = useState<Article>(initData);
  const [scrollElement,setScrollElement] = useState<HTMLElement>();

  useEffect(()=>{
    setScrollElement(document.documentElement)   
     
  },[])

  
  return (
    <div className={styles.article_wrap}>
      <div className={styles.article_content} id="md">
            <h2>{articleDetail.title}</h2>
            <MdPreview
              editorId={id}
              className={styles.md_preview}
              modelValue={articleDetail.content as string}
              previewTheme="smart-blue"
            />
          </div>
          <div className={styles.md_cat}>
            <MdCatalog editorId={id} scrollElement={scrollElement} />
          </div>
    </div>
  );
}

export async function getStaticProps() {
  const initData: Article = await request.post(APIS.ARTICLE_DETAIL, {id:99999});
  return {
    props: {
      initData
    }
  };
}

export default About;

// css
.article_wrap {
  padding: 15px 0;
  width: 400px;
  margin: 0 auto;
  display: flex;
  gap: 10px;
  position: relative;
  .article_content {
    background-color: #fff;
    border-radius: 4px;

    & > h2 {
      padding-top: 8px;
      font-size: 12px;
      text-align: center;
    }
  }
  .md_cat {
    width: 400px;
    padding: 10px;
    max-height: 50vh;
    background: #fff;
    border-radius: 4px;
    position: sticky;
    top: 30px;
    left: 400px;
    overflow-y: auto;
  }
}

这里无论是左侧预览滚动时右侧MdCatalog不会高亮显示
还是点击MdCatalog标题，左侧也不会滚动
是bug呢，还是我的哪一步出了问题

### Procedure version

"md-editor-rt": "^4.3.0"

**Comment by BenjaminCCG** [comment]
由于在nextjs中document会提示not defind 所以只能在useEffect中去赋值

**Comment by imzbf** [comment]
> 由于在nextjs中document会提示not defind 所以只能在useEffect中去赋值

字符串也可以，你尝试赋值为`html`

**Comment by BenjaminCCG** [comment]
> > 由于在nextjs中document会提示not defind 所以只能在useEffect中去赋值
> 
> 字符串也可以，你尝试赋值为`html`

感谢，成功解决
