### ISSUE TITLE
在next13 approuter 模式下，声明document.documentElement会导致无法ssr渲染？

### ISSUE THREAD

**Issue by xiaoxing92** [imzbf/md-editor-rt#102]
### Describe the issue

在next13 appRouter模式下，服务端组件包裹客户端组件，因为MdCatalog组件scrollElement需要绑定dom节点，但是在客户端组件里使用了document.documentElement就会导致整个页面都走客户端渲染了，无法ssr了，不用document.documentElemen，MdCatalog组件又无法滚动到对应锚点，有什么办法解决？

如下代码：
```js

const MdView = (props) => {
  const scrollElement = document.documentElement;
  return (
    <>
      <div>
        <MdPreview editorId="preview-only" modelValue={props.data} />
      </div>
      <MdCatalog editorId="preview-only" scrollElement={scrollElement} />
    </>
  );
};
export default memo(MdView);

```

### Procedure version

4.3.1-beta.0

**Comment by imzbf** [comment]
参考这里 #90

服务端设置滚动原生参考这里 https://github.com/imzbf/md-editor-rt/issues/101#issuecomment-1685222297

**Comment by xiaoxing92** [comment]
> 如果是新模式报错，参考这里 #90
> 
> 服务端设置滚动原生参考这里 [#101 (comment)](https://github.com/imzbf/md-editor-rt/issues/101#issuecomment-1685222297)

还有一个问题想问下作者，MdPreview 组件支持移动端自适应吗
