### ISSUE TITLE
How to custom the syntax transformation rules of MdPreview

### ISSUE THREAD

**Issue by destiny4** [imzbf/md-editor-rt#103]
### Describe the issue

i want to custom the syntax transformation rules of MdPreview

how can i do 

### Procedure version

4.3.0

**Comment by imzbf** [comment]
refer to: [markdownItConfig](https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%8D%A4%20markdownItConfig)

**Comment by destiny4** [comment]
> refer to: [markdownItConfig](https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%8D%A4%20markdownItConfig)

thx , how can i transform a keywords  

like ${keyword}

to

realvalue

on prewiew

eg:
 tranform ${keyword} to realvalue

the effect is:

on editor:
-----------------
thisi is example ${keyword}
-----------------
on preview

this is example realvalue

**Comment by imzbf** [comment]
Sorry, I have no idea about this, perhaps, you need to get more examples about `markdowk-it`. https://www.npmjs.com/search?q=keywords:markdown-it-plugin

**Comment by destiny4** [comment]
> Sorry, I have no idea about this, perhaps, you need to get more examples about `markdowk-it`. https://www.npmjs.com/search?q=keywords:markdown-it-plugin

thx，get it！
