### ISSUE TITLE
how can i cancel a plugin like  katex

### ISSUE THREAD

**Issue by destiny4** [imzbf/md-editor-rt#104]
### Describe the issue

i don't want to use katex's conversion rule

how can i avoid this katex rule

use noKatex prop only cancel the style of element, the  katex's conversion rule also exist

### Procedure version

4.3.0

**Comment by imzbf** [comment]
If `KatexPlugin` for `markdown-it` really hinders you. There is as way to remove it.

```js
import { config } from 'md-editor-rt';

config({
  markdownItPlugins(plugins) {
    return plugins.filter((p) => p.type !== 'katex');
  }
});
```
