### ISSUE TITLE
Could not work with nextjs v13 appdir

### ISSUE THREAD

**Issue by taoqf** [imzbf/md-editor-rt#105]
### 描述这个Bug

could not preview mermaid.

### 版本号

nodejs v18 nextjs v13

**Comment by imzbf** [comment]
`'use client';` may need to be set in your page.

**Comment by taoqf** [comment]
Maybe it's not 'use client' cause this issue. 
I do have 'use client' in my page.
I find when refresh preview, the image would show for a very shot time, after that, seems like something clear mermaid and the chart would disappear.

And, there is a warning 
```log
- warn ./node_modules/.pnpm/md-editor-rt@4.4.0_@codemirror+state@6.2.1_@codemirror+view@6.17.0_@lezer+common@1.0.4_react-dom@18.2.0_react@18.2.0/node_modules/md-editor-rt/lib/cjs/chunks/Editor.cjs
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/.pnpm/md-editor-rt@4.4.0_@codemirror+state@6.2.1_@codemirror+view@6.17.0_@lezer+common@1.0.4_react-dom@18.2.0_react@18.2.0/node_modules/md-editor-rt/lib/cjs/chunks/Editor.cjs
./node_modules/.pnpm/md-editor-rt@4.4.0_@codemirror+state@6.2.1_@codemirror+view@6.17.0_@lezer+common@1.0.4_react-dom@18.2.0_react@18.2.0/node_modules/md-editor-rt/lib/cjs/index.cjs
./src/app/page.tsx
```

this is my test code

src/app/page.tsx

```tsx
'use client';

import { MdEditor } from 'md-editor-rt';
import 'md-editor-rt/lib/style.css';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Page() {
	const [text, setText] = useState('# md-editor-v3');

	return (
		<div className={styles.container}>
			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing <code className={styles.code}>pages/index.js</code>
				</p>

				<MdEditor modelValue={text} onChange={setText} />
			</main>
		</div>
	);
}
```

I just change the example code, and using with next@latest and react@latest

**Comment by taoqf** [comment]
这个问题的原因我找到并且验证了，但我没找到最优美的解决办法。@imzbf 能否给出更好的解决办法呢？原因如下：
在useMarkdownIt中`replaceMermaid`的调用过早了，因为html的变化会导致`replaceMermaid`的调用，但html的变化同样会导致`ContentPreview`中html的变化，而html的变化会导致在预览中将`replaceMermaid`生成的图被替换掉。我现在的解决办法是在`useMarkdownIt`中将`replaceMermaid`的调用推迟10毫秒。但是你知道，这个10毫秒它不是一个理想值，因为你不可能确定在不同的电脑上这个值是否可靠。

**Comment by imzbf** [comment]
> 这个问题的原因我找到并且验证了，但我没找到最优美的解决办法。@imzbf 能否给出更好的解决办法呢？原因如下： 在useMarkdownIt中`replaceMermaid`的调用过早了，因为html的变化会导致`replaceMermaid`的调用，但html的变化同样会导致`ContentPreview`中html的变化，而html的变化会导致在预览中将`replaceMermaid`生成的图被替换掉。我现在的解决办法是在`useMarkdownIt`中将`replaceMermaid`的调用推迟10毫秒。但是你知道，这个10毫秒它不是一个理想值，因为你不可能确定在不同的电脑上这个值是否可靠。

这里确实有个问题，作者没注意到，它在正常的单页应用中没有影响，但是在next中有问题，我尝试修复看看

不过我刚刚没有能还原你这边报错的问题，可能需要这边修复后通过测试版这边协助验证一下

**Comment by taoqf** [comment]
https://github.com/taoqf/test-md-editor-rt
就这样就可以，很容易复现的呀

**Comment by imzbf** [comment]
> https://github.com/taoqf/test-md-editor-rt 就这样就可以，很容易复现的呀

我忘记我的next13环境解决过这个问题了，所以没复现，这个问题是因为动态的import导致的，需要对next进行一点配置

next.config.js

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve = {
        ...config.resolve,
        fallback: {
          ...config.resolve.fallback,
          fs: false,
        },
      };
    }
    config.module = {
      ...config.module,
      exprContextCritical: false,
    };
    return config;
  },
};

module.exports = nextConfig;
```

**Comment by imzbf** [comment]
> 这个问题的原因我找到并且验证了，但我没找到最优美的解决办法。@imzbf 能否给出更好的解决办法呢？原因如下： 在useMarkdownIt中`replaceMermaid`的调用过早了，因为html的变化会导致`replaceMermaid`的调用，但html的变化同样会导致`ContentPreview`中html的变化，而html的变化会导致在预览中将`replaceMermaid`生成的图被替换掉。我现在的解决办法是在`useMarkdownIt`中将`replaceMermaid`的调用推迟10毫秒。但是你知道，这个10毫秒它不是一个理想值，因为你不可能确定在不同的电脑上这个值是否可靠。

另外，我在`4.5.0-beta.1`中修复了这个问题，你可以通过下面的方式安装，4.5的文档没有发布，可以暂时忽略新增的功能

```shell
pnpm i md-editor-rt@beta
```

**Comment by imzbf** [comment]
Latest version has been released
