### ISSUE TITLE
在我向编辑器插入了几张图片后，左右同步滚动的位置似乎不太同步。

### ISSUE THREAD

**Issue by Fuzhang1** [imzbf/md-editor-rt#109]
### Describe the issue

当我在编辑器中插入了几张图片，启动同步滚动，每次在编辑器文本尾部添加新的文本内容时，同步滚动总是帮我回到不正确的位置如图所示。
![image](https://github.com/imzbf/md-editor-rt/assets/107840435/8c0033fa-9258-48c6-b33c-ff7e8f40e2f6)
有什么好的方法可以帮助我解决这个问题吗，比如说我可以重载滚动事件或者一些其它的操作。

### Procedure version

nodejs:  v16.17.0

**Comment by imzbf** [comment]
这好像没有合适的优化方案，因为左边没有滚动条，它不会被认为已经滚到底部了，建议这种情况的时候不启用同步滚动
