### ISSUE TITLE
feat：功能

### ISSUE THREAD

**Issue by gujiwuqing** [imzbf/md-editor-rt#11]
大佬 后续能新增给某些文字变色 然后预览模式下能弄目录吗

**Comment by imzbf** [comment]
- markdown编辑器不会过多的对文本样式进行设置，在后续版本中可能会提供状态栏自定义功能，目前正在考虑实现方式。
- 关于预览模式下的目录，该组件有提供内容的标题扁平结构，请通过相应的api进行使用，可参考组件文档分支代码。

**Comment by gujiwuqing** [comment]
好的 收到 谢谢大佬
