### ISSUE TITLE
Preview to update editor

### ISSUE THREAD

**Issue by OriginalPato** [imzbf/md-editor-rt#114]
### A great idea

I've looked over the docs a few time to see if this is already possible but have not been able to see anything showing that it is. I am looking to see if it would be possible for the Preview to update as well (example below)

When you tick or untick a checkbox (- [ ]) in the preview can it update in the editor?

Thanks in advance!

**Comment by imzbf** [comment]
I don't have a technology proposal yet. Let me have a try.

**Comment by imzbf** [comment]
Sorry, on consideration, we are prepared to abandon this kind of feature: updating content in the preview area.
It is more suitable for WYSIWYG. But we have already given up implementing this mode.
