### ISSUE TITLE
Include the imgresize, mark, emoji and pop-up preview to the default toolbar

### ISSUE THREAD

**Issue by Udayendu** [imzbf/md-editor-rt#115]
### A great idea

Currently these features are not part of the default toolbar. It would be nice if we can add them by default. If not required, some one should be able to disable them by `toolbarsExclude` entry.

**Comment by imzbf** [comment]
`toolbarsExclude` does work, but inner components do not support on-demand referencing.

If someone does not need component `ExportPDF`. It will still appear in his project.

`md-editor-extension` is the better solution currently.

**Comment by Udayendu** [comment]
@imzbf Thanks for the update. I am not talking about the complete components. Just add those 3-4 components as we discussed in https://github.com/imzbf/md-editor-rt/issues/91#issuecomment-1763308266 

`ExportPDF` is a heavy duty plugin. So may be we can keep that separate. 

For me primary issue is, I am not getting the icons as you have mentioned to use.

**Comment by imzbf** [comment]
> @imzbf Thanks for the update. I am not talking about the complete components. Just add those 3-4 components as we discussed in [#91 (comment)](https://github.com/imzbf/md-editor-rt/issues/91#issuecomment-1763308266)
> 
> `ExportPDF` is a heavy duty plugin. So may be we can keep that separate.
> 
> For me primary issue is, I am not getting the icons as you have mentioned to use. If required, I can use those from the MUI Icon.

About icons, I am trying to add default icon. There are still unresolved issues at present😅.

**Comment by Udayendu** [comment]
For now I have added the MUI icon and they are working fine:

![image](https://github.com/imzbf/md-editor-rt/assets/1809177/e2220fc7-0ba1-4d17-a0d9-dd0cc7a0648e)

But emoji are not showing in tabular mode. Its showing via sequential numbers though working well.

```
            defToolbars={[
              <OriginalImg
                key="OriginalImg"
                trigger={<AspectRatioIcon fontSize="24px" />}
                title="imgresize"
              />,
              <Mark
                key="Mark"
                trigger={<BookmarkBorderOutlinedIcon fontSize="24px" />}
                title="mark"
              />,
              <Emoji
                key="Emoji"
                trigger={<EmojiEmotionsOutlinedIcon fontSize="24px" />}
                title="emoji"
              />,
            ]}
          />
```

**Comment by imzbf** [comment]
> For now I have added the MUI icon and they are working fine:
> 
> ![image](https://user-images.githubusercontent.com/1809177/280524340-e2220fc7-0ba1-4d17-a0d9-dd0cc7a0648e.png)
> 
> But emoji are not showing in tabular mode. Its showing via sequential numbers though working well.
> 
> ```
>             defToolbars={[
>               <OriginalImg
>                 key="OriginalImg"
>                 trigger={<AspectRatioIcon fontSize="24px" />}
>                 title="imgresize"
>               />,
>               <Mark
>                 key="Mark"
>                 trigger={<BookmarkBorderOutlinedIcon fontSize="24px" />}
>                 title="mark"
>               />,
>               <Emoji
>                 key="Emoji"
>                 trigger={<EmojiEmotionsOutlinedIcon fontSize="24px" />}
>                 title="emoji"
>               />,
>             ]}
>           />
> ```

They are not showing?
<img width="417" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/37092006/bd95d799-0bc9-4951-b566-752a102c7067">

**Comment by Udayendu** [comment]
> > For now I have added the MUI icon and they are working fine:
> > ![image](https://user-images.githubusercontent.com/1809177/280524340-e2220fc7-0ba1-4d17-a0d9-dd0cc7a0648e.png)
> > But emoji are not showing in tabular mode. Its showing via sequential numbers though working well.
> > ```
> >             defToolbars={[
> >               <OriginalImg
> >                 key="OriginalImg"
> >                 trigger={<AspectRatioIcon fontSize="24px" />}
> >                 title="imgresize"
> >               />,
> >               <Mark
> >                 key="Mark"
> >                 trigger={<BookmarkBorderOutlinedIcon fontSize="24px" />}
> >                 title="mark"
> >               />,
> >               <Emoji
> >                 key="Emoji"
> >                 trigger={<EmojiEmotionsOutlinedIcon fontSize="24px" />}
> >                 title="emoji"
> >               />,
> >             ]}
> >           />
> > ```
> 
> They are not showing? <img alt="image" width="417" src="https://user-images.githubusercontent.com/37092006/280531619-bd95d799-0bc9-4951-b566-752a102c7067.png">

No. They are showing like a list:

1. ![image](https://github.com/imzbf/md-editor-rt/assets/1809177/c79bc2bd-9b32-4a9c-906b-460338ce104e)
2. ![image](https://github.com/imzbf/md-editor-rt/assets/1809177/a2803099-a2f9-435f-bd82-df2f087bf677)
[...]

This is just to show you. But yes, they are coming like a list instead of a tabular format.

**Comment by imzbf** [comment]
> No. They are showing like a list:
> 
> 1. ![image](https://user-images.githubusercontent.com/1809177/280532249-c79bc2bd-9b32-4a9c-906b-460338ce104e.png)
> 2. ![image](https://user-images.githubusercontent.com/1809177/280532331-a2803099-a2f9-435f-bd82-df2f087bf677.png)
>    [...]
> 
> This is just to show you. But yes, they are coming like a list instead of a tabular format.

Maybe you did not import css 

```js
import '@vavt/rt-extension/lib/asset/Emoji.css';
```

**Comment by imzbf** [comment]
Each component in ``@vavt/rt-extension`` has default icon set for `trigger`. Try install the latest version.

**Comment by Udayendu** [comment]
> #91 (comment)

Thanks @imzbf . After importing the .css file, it worked well.

**Comment by Udayendu** [comment]
> @vavt/rt-extension

Tested with the new version and its working well. Thanks a lot for the fix.
