### ISSUE TITLE
请问codeTheme 能指定是dark还是light吗

### ISSUE THREAD

**Issue by one-dragon** [imzbf/md-editor-rt#116]
### Describe the issue

请问codeTheme 能指定是dark还是light吗~

### Procedure version

"md-editor-rt": "^4.8.3"

**Comment by imzbf** [comment]
能呀
https://imzbf.github.io/md-editor-rt/zh-CN/docs#%F0%9F%9B%81%20codeStyleReverse

**Comment by one-dragon** [comment]
![image](https://github.com/imzbf/md-editor-rt/assets/20273665/31506896-70b3-455b-a781-cbe1365f8aed)
不知道是不是我设置的问题 没好用
我给你看下我的代码：
import { useRef, useState } from 'react';
import { ExposeParam, MdEditor, config } from 'md-editor-rt';
import 'md-editor-rt/lib/style.css';
import { Emoji, Mark, ExportPDF } from '@vavt/rt-extension';
import '@vavt/rt-extension/lib/asset/style.css';

import MarkExtension from 'markdown-it-mark';
import { lineNumbers } from '@codemirror/view';


import ReadExtension from './ReadExtension';
import TimeNow from './TimeNow';

import './iconfont1';
import './iconfont2';


import { useStore } from '@src/hooks';

const highlightJs = new URL('./lib/highlight.js/index.min.js', import.meta.url).href;
const highlightAtomDarkCss = new URL('./lib/highlight.js/atom-one-dark.min.css', import.meta.url).href;
const highlightAtomLightCss = new URL('./lib/highlight.js/atom-one-light.min.css', import.meta.url).href;
console.log(highlightAtomDarkCss);
console.log(highlightAtomLightCss);

const editorId = 'editor-preview';
config({
  markdownItConfig(md) {
    md.use(MarkExtension);
  },
  codeMirrorExtensions(theme, extensions) {
    const exs = [...extensions, lineNumbers()];

    // exs[1] = basicSetup;
    return exs;
  },
  editorExtensions: {
    highlight: {
      js: highlightJs,
      css: {
        atom: {
          dark: highlightAtomDarkCss,
          light: highlightAtomLightCss,
        },
      },
    },
  },
  editorConfig: {
    // languageUserDefined: {
    //   ZH_TW
    // }
  },
});

const MarkDown = () => {
  const { markdown: { config } } = useStore();

  const editorRef = useRef<ExposeParam>();

  const [md, setMd] = useState('hello md-editor-rt！');
  return (
    <div className="project-preview">
      <div className="container">
        <MdEditor
          style={{
            height: 800,
          }}
          showCodeRowNumber
          autoDetectCode
          codeStyleReverse={false}
          noUploadImg={false}
          ref={editorRef}
          theme={config.theme}
          previewTheme={config.previewTheme}
          codeTheme={config.codeTheme}
          modelValue={md}
          language={config.lang}
          editorId={editorId}
          defToolbars={[
            <Mark key="mark-extension" />,
            <Emoji key="emoji-extension" />,
            <ReadExtension mdText={md} key="read-extension" />,
            <ExportPDF key="ExportPDF" modelValue={md} height="700px" />,
          ]}
          onSave={(v, h) => {
            console.log('v', v);

            h.then((html) => {
              console.log('h', html);
            });
          }}
          toolbars={[
            'bold',
            'underline',
            'italic',
            'strikeThrough',
            '-',
            'title',
            'sub',
            'sup',
            'quote',
            'unorderedList',
            'orderedList',
            'task',
            '-',
            'codeRow',
            'code',
            'link',
            'image',
            'table',
            'mermaid',
            'katex',
            0,
            1,
            2,
            3,
            '-',
            'revoke',
            'next',
            'save',
            '=',
            'prettier',
            'pageFullscreen',
            'fullscreen',
            'preview',
            'htmlPreview',
            'catalog',
            'github',
          ]}
          onChange={(value: string) => setMd(value)}
          // onUploadImg={async (files: Array<File>, callback: (urls: string[]) => void) => {
          //   const res = await Promise.all(
          //     files.map((file) => {
          //       return new Promise((rev, rej) => {
          //         const form = new FormData();
          //         form.append('file', file);

          //         axios
          //           .post('/api/img/upload', form, {
          //             headers: {
          //               'Content-Type': 'multipart/form-data'
          //             }
          //           })
          //           .then((res: any) => rev(res))
          //           .catch((error: any) => rej(error));
          //       });
          //     })
          //   );

          //   callback(res.map((item: any) => item.data.url));
          // }}
          footers={['markdownTotal', '=', 0, 'scrollSwitch']}
          defFooters={[<TimeNow key="time-now" />]}
        />
      </div>
    </div>
  );
};

export default MarkDown;

**Comment by one-dragon** [comment]
我设置 codeStyleReverse={false} 但是还是黑色的code主题

**Comment by one-dragon** [comment]
![image](https://github.com/imzbf/md-editor-rt/assets/20273665/644ff178-9240-49c7-ac38-434e231c0584)
还发现个问题~就是如果用sanitize-html处理生成的html 导致公式不好用了~

**Comment by imzbf** [comment]
![image](https://github.com/imzbf/md-editor-rt/assets/37092006/a68873f5-06f1-4484-a46c-7fc12e063894)

这样，`dev-docs`里的`main.ts`有

**Comment by imzbf** [comment]
> ![image](https://user-images.githubusercontent.com/20273665/284850842-644ff178-9240-49c7-ac38-434e231c0584.png) 还发现个问题~就是如果用sanitize-html处理生成的html 导致公式不好用了~

不再建议使用这个了，内置了危险标签处理

**Comment by imzbf** [comment]
> ![image](https://user-images.githubusercontent.com/37092006/284923723-a68873f5-06f1-4484-a46c-7fc12e063894.png)
> 
> 这样，`dev-docs`里的`main.ts`有

https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/main.ts#L42
