### ISSUE TITLE
我在内网环境使用md-editor-rt时，由于内部依赖库引用了cdn的资源。有办法把它们替换为本地资源吗？

### ISSUE THREAD

**Issue by programmermark** [imzbf/md-editor-rt#117]
### Describe the issue

我在内网环境使用md-editor-rt时，由于内部依赖库引用了cdn的资源。有办法把它们替换为本地资源吗？

### Procedure version

browser

**Comment by imzbf** [comment]
两种方式
https://imzbf.github.io/md-editor-rt/zh-CN/demo#%F0%9F%93%A1%20%E5%86%85%E7%BD%91%E9%93%BE%E6%8E%A5

https://imzbf.github.io/md-editor-rt/zh-CN/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93

**Comment by programmermark** [comment]
@imzbf 感谢，这些我在文档没搜索到。
补充一下，上面的自行引入扩展库引的文档示例中缺失了 standalone的引入。另外，iconfront仍旧会出现在外部资源中。
这是我在本地实际使用后完整的示例：


`
import "highlight.js/styles/atom-one-dark.css";

import Cropper from "cropperjs";
import highlight from "highlight.js";
import katex from "katex";
import { config } from "md-editor-rt";
import mermaid from "mermaid";
// <3.0
import prettier from "prettier";
import parserMarkdown from "prettier/plugins/markdown";
import screenfull from "screenfull";

// https://at.alicdn.com/t/c/font_2605852_u82y61ve02.js
import iconfont from "@/common/externals/md-editor-rt/iconfont/md-editor-iconfont.min.js?url";
import standaloneJs from "@/common/externals/prettier/standalone.js?url";

/**
 * 配置编辑器外部依赖源为本地资源，而不是cdn
 */
export function configMDEditor() {
  config({
    iconfontType: "svg",
    editorExtensions: {
      iconfont: iconfont,
      prettier: {
        prettierInstance: prettier,
        parserMarkdownInstance: parserMarkdown,
        standaloneJs: standaloneJs
      },
      highlight: {
        instance: highlight
      },
      screenfull: {
        instance: screenfull
      },
      katex: {
        instance: katex
      },
      cropper: {
        instance: Cropper
      },
      mermaid: {
        instance: mermaid
      }
    }
  });
}
`

**Comment by lai397826696** [comment]
> 两种方式 https://imzbf.github.io/md-editor-rt/zh-CN/demo#%F0%9F%93%A1%20%E5%86%85%E7%BD%91%E9%93%BE%E6%8E%A5
> 
> https://imzbf.github.io/md-editor-rt/zh-CN/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93

内网链接还是会报错
![image](https://github.com/imzbf/md-editor-rt/assets/13134964/ef314700-4795-4e98-a28d-e3601ea1fdde)

![image](https://github.com/imzbf/md-editor-rt/assets/13134964/04ed903c-23a5-4b9f-966a-abf5afbe625f)

ps: js文件可以额外打开的

**Comment by lai397826696** [comment]
![image](https://github.com/imzbf/md-editor-rt/assets/13134964/cc4065fe-4776-4135-ab0b-7a9933744fd8)

**Comment by imzbf** [comment]
> ![image](https://private-user-images.githubusercontent.com/13134964/298002351-cc4065fe-4776-4135-ab0b-7a9933744fd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDI2NjksIm5iZiI6MTcwNTg0MjM2OSwicGF0aCI6Ii8xMzEzNDk2NC8yOTgwMDIzNTEtY2M0MDY1ZmUtNDc3Ni00MTM1LWFiMGItN2E5OTMzNzQ0ZmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEzMDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZDIxZDM3NTZjNTkxZmQxZWM4MTkzNTIzYzVjMDQ4ODE0Yjg0NzNlMzIwN2Q5OTRiYTkzN2JmMzgyZTA1YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dL3az4BHTTOg8Sqleo40YeSS65E7LE2KV7h5XUZK9dA)

你setURL没有完整的链接，没有域名或者明确的IP和协议
