### ISSUE TITLE
编辑器模式  preview={false} 的bug

### ISSUE THREAD

**Issue by KevinYouu** [imzbf/md-editor-rt#118]
### 描述这个Bug

preview设置为false时, 右侧预览区域和分割线仍然存在,手动点击预览图标后开启然后关闭一次就消失了

<img width="1116" alt="截屏2023-11-27 19 31 32" src="https://github.com/imzbf/md-editor-rt/assets/46970005/a40c1769-449d-4b6f-970c-27ccc8d99428">

https://github.com/imzbf/md-editor-rt/assets/46970005/f70493a8-7969-4154-87e7-7bcf4a38283b

### 版本号

4.8.3

**Comment by imzbf** [comment]
在4.9.0中已修复，请更新后尝试
