### ISSUE TITLE
The arrow on the mermaid diagram is not displayed on google chrome.

### ISSUE THREAD

**Issue by escoda-hub** [imzbf/md-editor-rt#120]
### Describe the issue

Hi,
Thank you for developing such a great library.
I found the problem and would like to share it.

## Issue overview
When drawing a diagram in Mermaid, the arrow disappears in Google Chrome.

## Steps to reproduce the issue
1. check diagram on https://imzbf.github.io/md-editor-rt/en-US/index
2. arrow not visible
![スクリーンショット 2023-11-28 22 06 23](https://github.com/imzbf/md-editor-rt/assets/33148369/402fc941-5d35-48ed-ac7c-733f3d03f8b4)

## environment
- md-editor-rt@4.8.3
- Chrome Version: 119.0.6045.159 (Official Build) (arm64)
- Apple M1 Pro

## cause analysis
When comparing path element between [marmaid live editor](https://mermaid.live/edit#pako:eNoljDEKwzAQBL8itrY_oCKVf2CX1xzSJTaxJHOcCMH47zmTbpgd9kRqWRBBlepzb5-0slpYJqohzHbzOD6c2oEBRbTwlj0_751gqxQhRMfM-ia_ubzjbm3-1oRo2mVAPzKbTBu_lMtfXj-lnCkE) and [imzbf](https://imzbf.github.io/md-editor-rt/en-US/index) on chrome devtools, ```marker-end``` property of the path element is different.

-  mermaid live editor : ```url(#graph-div_flowchart-pointEnd)``` 
- imzbf : ```url(#flowchart-pointEnd)```)

<img width="1265" alt="スクリーンショット 2023-11-28 22 32 14" src="https://github.com/imzbf/md-editor-rt/assets/33148369/0a5b7d3b-8c7e-411e-b707-27f7d5d4d7ad">

## Supplementary information
On Safari version 16.5.2 (18615.2.9.11.10) , an arrow on the mermaid diagram will appear correctly.
<img width="1160" alt="スクリーンショット 2023-11-28 22 17 53" src="https://github.com/imzbf/md-editor-rt/assets/33148369/854fdc59-a8f6-4c67-8073-1dc90945c928">

If there is anything I can do to help solve a problem, I will share it.
Thank you.

### Procedure version

Chrome Version: 119.0.6045.159 (Official Build) (arm64)

**Comment by imzbf** [comment]
Upgrade `mermaid`

```js
config({
  editorExtensions: {
    mermaid: {
      js: 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.1/mermaid.esm.min.mjs'
    }
  }
});
```
