### ISSUE TITLE
感觉是umi与md-editor-rt兼容问题

### ISSUE THREAD

**Issue by 934187210** [imzbf/md-editor-rt#122]
### Describe the issue

<img width="1215" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/75872840/1e65bbb2-a615-40b6-96a8-76bf44445a1e">

### Procedure version

  "umi": "^3.2.17",   node：v14,  "md-editor-rt": "^4.9.0",

**Comment by imzbf** [comment]
我尝试创建了一个基础项目，好像还原不了。这可能和你其他的扩展报的。

**Comment by 934187210** [comment]
在另一个空壳项目也试了都不行，都是umi v3版本。node v14。下面是全部报错
<img width="1678" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/75872840/08597fe7-b73f-49c3-b552-e5497906a961">

**Comment by imzbf** [comment]
> 在另一个空壳项目也试了都不行，都是umi v3版本。node v14。下面是全部报错 <img alt="image" width="1678" src="https://private-user-images.githubusercontent.com/75872840/288604103-08597fe7-b73f-49c3-b552-e5497906a961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzMzMTIsIm5iZiI6MTcwMTkzMzAxMiwicGF0aCI6Ii83NTg3Mjg0MC8yODg2MDQxMDMtMDg1OTdmZTctYjczZi00OWMzLWI1NTItZTU0OTc5MDZhOTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA3MTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YjlkMmRlOGQzZTIyMGE3ODJkMDY2Yjk5Y2Y1NTI4MDlhOTNmY2NkZTk3ZTZiZmMzZTBlMTEwNDA1YmQ2ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sh2kxrX0oFsfBt3E9MLLK__PIgwY2rFsCuIn_X76Efw">

把你的空壳项目打包过来看看

**Comment by imzbf** [comment]
如果升级成本不高，建议升级对应的框架版本

**Comment by lai397826696** [comment]
刚刚用umijs创建的一个简单的react应用，还是会报错，无法正常显示，"md-editor-rt": "^4.11.0"，"umi": "^4.1.1"，node: 16.16.0
![image](https://github.com/imzbf/md-editor-rt/assets/13134964/85f1c5e4-da9e-424e-8cff-1473811703c7)
![image](https://github.com/imzbf/md-editor-rt/assets/13134964/1c575581-52f8-4855-8fce-3db9f43e9f0d)
![image](https://github.com/imzbf/md-editor-rt/assets/13134964/f2788587-4a92-4d09-9d5d-2c6a14d48a3c)

**Comment by imzbf** [comment]
> 刚刚用umijs创建的一个简单的react应用，还是会报错，无法正常显示，"md-editor-rt": "^4.11.0"，"umi": "^4.1.1"，node: 16.16.0 ![image](https://private-user-images.githubusercontent.com/13134964/297975941-85f1c5e4-da9e-424e-8cff-1473811703c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDI4NTcsIm5iZiI6MTcwNTg0MjU1NywicGF0aCI6Ii8xMzEzNDk2NC8yOTc5NzU5NDEtODVmMWM1ZTQtZGE5ZS00MjRlLThjZmYtMTQ3MzgxMTcwM2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEzMDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YzJhYmYwZmE1NDljNTY4OGQwNWE2MWUwYmNjYzQ4OGExZWVkN2UxNTRkYjJlZjk2OTRmNDE1YzI2MTg2N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BEHJrn5JwntXYq4nAFsFHv2aE3j3Wlp0rvQ8uziS4UY) ![image](https://private-user-images.githubusercontent.com/13134964/297976330-1c575581-52f8-4855-8fce-3db9f43e9f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDI4NTcsIm5iZiI6MTcwNTg0MjU1NywicGF0aCI6Ii8xMzEzNDk2NC8yOTc5NzYzMzAtMWM1NzU1ODEtNTJmOC00ODU1LThmY2UtM2RiOWY0M2U5ZjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEzMDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwODc4OWY0YWM5ODg0MGVkNjJhYjdhZGUxNWNjN2VlMjNkYmJiNTM1ZWJkMDFjMzdkYzhmOWQ4ODk3NDc4MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h4erkiY_s3eiZBh6X39tDByoKwbYfWR_O23GeyM6_pc) ![image](https://private-user-images.githubusercontent.com/13134964/297976406-f2788587-4a92-4d09-9d5d-2c6a14d48a3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDI4NTcsIm5iZiI6MTcwNTg0MjU1NywicGF0aCI6Ii8xMzEzNDk2NC8yOTc5NzY0MDYtZjI3ODg1ODctNGE5Mi00ZDA5LTlkNWQtMmM2YTE0ZDQ4YTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEzMDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MTg3YTRmMDk1ZTVlNjNmNzY3NTk1MjNjMDRhNTlkZjJlNTA4ODVkMjhlZmMxZWViY2IyNzJjMmQ3NzBlNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0R3WrVEi8pdRe1rkvRbl4rQrzIPonbbjFwD7em6A6hY)

方便的话提供一下这个模版
