### ISSUE TITLE
MD Quotes not working on preview-only mode

### ISSUE THREAD

**Issue by shaipetel** [imzbf/md-editor-rt#123]
### 描述这个Bug

Setting this markdown value:
``` markdown
# Hello header
> description
## Sub header
```
to the MdPreview control:
``` react
<MdPreview key={`zone:${lz}`} editorId={`zone_${lz}`} modelValue={zones[lz]} />
```

produces the right html for most controls, including mermaid charts - except for the block quote for lines starting with 
"> "

Using the same text for the editor works fine.

### 版本号

node 16.19.0

**Comment by imzbf** [comment]
<img width="1105" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/37092006/fcf88f87-7aec-404b-81bd-0d61576f0151">

It's working
