### ISSUE TITLE
在ant pro中新版 md-editor-rt 编辑器展示了三栏且滚动有问题

### ISSUE THREAD

**Issue by Evenz** [imzbf/md-editor-rt#126]
### Describe the issue

初始状态同时展示了编辑页，预览页和html代码页，无法关闭，最左侧编辑栏无法滚动

<img width="1160" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/7604337/5c6539fe-73e9-4df8-bf85-c3453a26d9dc">

### Procedure version

4.9.0

**Comment by Evenz** [comment]
从 v2 升级到 v4

**Comment by imzbf** [comment]
麻烦提供下还原问题的代码

**Comment by Evenz** [comment]
import React from 'react';
import { MdEditor, NormalToolbar } from 'md-editor-rt';
import 'md-editor-rt/lib/style.css';
import MarkExtension from './components/MarkExtension';
import EmojiExtension from './components/EmojiExtension';
import './index.less';
import AlignExtension from './components/AlignExtension';
import { DeleteOutlined } from '@ant-design/icons';

type PropsType = {
  editorId: string;
  value: string;
  onValueChange: (value: string) => void;
};

const MarkdownEditor: React.FC<PropsType> = (props) => {
  const { editorId, value, onValueChange } = props;

  const handleChangeValue = (content: string) => {
    if (onValueChange) onValueChange(content);
  };

  return (
    <div className="p-md-editor">
      <MdEditor
        editorId={editorId}
        modelValue={value}
        onChange={handleChangeValue}
        defToolbars={[
          <AlignExtension
            editorId={editorId}
            type="left"
            onChange={handleChangeValue}
            key="left-extension"
          />,
          <AlignExtension
            editorId={editorId}
            type="center"
            onChange={handleChangeValue}
            key="center-extension"
          />,
          <AlignExtension
            editorId={editorId}
            type="right"
            onChange={handleChangeValue}
            key="right-extension"
          />,
          <MarkExtension editorId={editorId} onChange={handleChangeValue} key="mark-extension" />,
          <EmojiExtension editorId={editorId} onChange={handleChangeValue} key="emoji-extension" />,
          <NormalToolbar
            key="empty-extension"
            title="清空"
            onClick={() => handleChangeValue('')}
            trigger={<DeleteOutlined style={{ marginTop: 5 }} />}
          />,
        ]}
        toolbars={[
          'bold',
          'underline',
          'italic',
          'strikeThrough',
          '-',
          'title',
          'sub',
          'sup',
          'quote',
          'unorderedList',
          'orderedList',
          'task',
          '-',
          0,
          1,
          2,
          '-',
          'codeRow',
          'code',
          'link',
          'image',
          'table',
          'mermaid',
          'katex',
          3,
          4,
          '-',
          'revoke',
          'next',
          5,
          '=',
          'prettier',
          'pageFullscreen',
          'fullscreen',
          'preview',
          'htmlPreview',
          'catalog',
        ]}
      />
    </div>
  );
};

export default MarkdownEditor;

**Comment by Evenz** [comment]
`import React from 'react';
import { MdEditor, NormalToolbar } from 'md-editor-rt';
import 'md-editor-rt/lib/style.css';
import MarkExtension from './components/MarkExtension';
import EmojiExtension from './components/EmojiExtension';
import './index.less';
import AlignExtension from './components/AlignExtension';
import { DeleteOutlined } from '@ant-design/icons';

type PropsType = {
  editorId: string;
  value: string;
  onValueChange: (value: string) => void;
};

const MarkdownEditor: React.FC<PropsType> = (props) => {
  const { editorId, value, onValueChange } = props;

  const handleChangeValue = (content: string) => {
    if (onValueChange) onValueChange(content);
  };

  return (
    <div className="p-md-editor">
      <MdEditor
        editorId={editorId}
        modelValue={value}
        onChange={handleChangeValue}
        defToolbars={[
          <AlignExtension
            editorId={editorId}
            type="left"
            onChange={handleChangeValue}
            key="left-extension"
          />,
          <AlignExtension
            editorId={editorId}
            type="center"
            onChange={handleChangeValue}
            key="center-extension"
          />,
          <AlignExtension
            editorId={editorId}
            type="right"
            onChange={handleChangeValue}
            key="right-extension"
          />,
          <MarkExtension editorId={editorId} onChange={handleChangeValue} key="mark-extension" />,
          <EmojiExtension editorId={editorId} onChange={handleChangeValue} key="emoji-extension" />,
          <NormalToolbar
            key="empty-extension"
            title="清空"
            onClick={() => handleChangeValue('')}
            trigger={<DeleteOutlined style={{ marginTop: 5 }} />}
          />,
        ]}
        toolbars={[
          'bold',
          'underline',
          'italic',
          'strikeThrough',
          '-',
          'title',
          'sub',
          'sup',
          'quote',
          'unorderedList',
          'orderedList',
          'task',
          '-',
          0,
          1,
          2,
          '-',
          'codeRow',
          'code',
          'link',
          'image',
          'table',
          'mermaid',
          'katex',
          3,
          4,
          '-',
          'revoke',
          'next',
          5,
          '=',
          'prettier',
          'pageFullscreen',
          'fullscreen',
          'preview',
          'htmlPreview',
          'catalog',
        ]}
      />
    </div>
  );
};

export default MarkdownEditor;
`

**Comment by Evenz** [comment]
``` JavaScript
import React from 'react';
import { MdEditor, NormalToolbar } from 'md-editor-rt';
import 'md-editor-rt/lib/style.css';
import MarkExtension from './components/MarkExtension';
import EmojiExtension from './components/EmojiExtension';
import './index.less';
import AlignExtension from './components/AlignExtension';
import { DeleteOutlined } from '@ant-design/icons';

type PropsType = {
  editorId: string;
  value: string;
  onValueChange: (value: string) => void;
};

const MarkdownEditor: React.FC<PropsType> = (props) => {
  const { editorId, value, onValueChange } = props;

  const handleChangeValue = (content: string) => {
    if (onValueChange) onValueChange(content);
  };

  return (
    <div className="p-md-editor">
      <MdEditor
        editorId={editorId}
        modelValue={value}
        onChange={handleChangeValue}
        defToolbars={[
          <AlignExtension
            editorId={editorId}
            type="left"
            onChange={handleChangeValue}
            key="left-extension"
          />,
          <AlignExtension
            editorId={editorId}
            type="center"
            onChange={handleChangeValue}
            key="center-extension"
          />,
          <AlignExtension
            editorId={editorId}
            type="right"
            onChange={handleChangeValue}
            key="right-extension"
          />,
          <MarkExtension editorId={editorId} onChange={handleChangeValue} key="mark-extension" />,
          <EmojiExtension editorId={editorId} onChange={handleChangeValue} key="emoji-extension" />,
          <NormalToolbar
            key="empty-extension"
            title="清空"
            onClick={() => handleChangeValue('')}
            trigger={<DeleteOutlined style={{ marginTop: 5 }} />}
          />,
        ]}
        toolbars={[
          'bold',
          'underline',
          'italic',
          'strikeThrough',
          '-',
          'title',
          'sub',
          'sup',
          'quote',
          'unorderedList',
          'orderedList',
          'task',
          '-',
          0,
          1,
          2,
          '-',
          'codeRow',
          'code',
          'link',
          'image',
          'table',
          'mermaid',
          'katex',
          3,
          4,
          '-',
          'revoke',
          'next',
          5,
          '=',
          'prettier',
          'pageFullscreen',
          'fullscreen',
          'preview',
          'htmlPreview',
          'catalog',
        ]}
      />
    </div>
  );
};

export default MarkdownEditor;

```

**Comment by imzbf** [comment]
<img width="1693" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/37092006/fd79e202-2566-4a0a-95e5-7df01e445e8b">
刚创建的，注意检查你项目里面的CSS对组件的影响，如果可以，提供可以还原问题并且可运行的项目

**Comment by Evenz** [comment]
好叻，谢谢，我先把css去掉弄一个纯净的试试

**Comment by Evenz** [comment]
找到原因了，缓存里v2的样式影响的，清了缓存就没事了
