### ISSUE TITLE
Unable to update the CSS Class 'md-editor-preview' for a particular page

### ISSUE THREAD

**Issue by Udayendu** [imzbf/md-editor-rt#127]
### Describe the issue

I have a requirement to update the CSS class for a particular page with 'md-editor-preview' for MdPreview. But that's impacting the whole app. How can I apply it to a particular page only ?

### Procedure version

4.10.0

**Comment by imzbf** [comment]
I'm not sure exactly what you're doing, could you give an example?

**Comment by Udayendu** [comment]
Let say I have two page. One to view multiple documents and one to view an individual one. I want different fonts, font size and colors to be applied on that. When I am trying to do that, Its overwriting the other one.

For an example, here is the css property which is setting all these:

```
.md-editor-preview {
  font-size: 16px;
  font-family: source-serif-pro, Georgia, Cambria, "Times New Roman", Times,
    serif;
  padding: 5px;
  color: #36443f;
}
```

But this seems to be global property and after setting it for one page, its not allowing me to set it for other pages.

**Comment by imzbf** [comment]
> Let say I have two page. One to view multiple documents and one to view an individual one. I want different fonts, font size and colors to be applied on that. When I am trying to do that, Its overwriting the other one.
> 
> For an example, here is the css property which is setting all these:
> 
> ```
> .md-editor-preview {
>   font-size: 16px;
>   font-family: source-serif-pro, Georgia, Cambria, "Times New Roman", Times,
>     serif;
>   padding: 5px;
>   color: #36443f;
> }
> ```
> 
> But this seems to be global property and after setting it for one page, its not allowing me to set it for other pages.

Thank you for your description, I have a solution

1. Set different class names for editors that require differentiation
2. Overlay styles based on different class names.

eg:

```jsx
import { MdEditor } from 'md-editor-rt';
import 'md-editor-rt/lib/style.css';

export default () => {
  return <><MdEditor class="c1" /><MdEditor class="c2" /></>;
};
```

```css
.c1 .md-editor-preview {
  font-size: 16px;
  font-family: source-serif-pro, Georgia, Cambria, "Times New Roman", Times,
    serif;
  padding: 5px;
  color: #36443f;
}

.c2 .md-editor-preview { 
  font-size: 18px;
}
```
