### ISSUE TITLE
文档的图片预览功能只能实现1:1的放大，同时没有一个入口可以方便地控制预览的入口，希望提供一个方式

### ISSUE THREAD

**Issue by programmermark** [imzbf/md-editor-rt#129]
### Describe the issue

文档的图片预览功能只能实现1:1的放大，同时没有一个入口可以方便地控制预览的入口，希望提供一个方式。
目前已知的方式是，人为获取预览的预览图片的节点，再去附加相关事件，但这种方式并不精准和优雅。

### Procedure version

md-editor-rt^4.8.2

**Comment by imzbf** [comment]
看了下用于预览的扩展库，好像没有API支持去调整放大的比例。如果需要更可控的方式，建议不使用内置的功能，设置`noImgZoomIn={true}`。

关于手动获取图片节点的问题，因为生成的内容是`html`文本而非相关库的虚拟`dom`节点，编辑器内部的实现也是通过获取节点添加监听事件的，目前没有更舒服的方式了

**Comment by programmermark** [comment]
感谢，我注意到了。
我看到了html渲染默认有500ms的演示，这是我没关注到的。
