### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by yuanyuanshan0627** [imzbf/md-editor-rt#130]
### Describe the issue

我在图片上传完成之后调用callback在页面显示
![image](https://github.com/imzbf/md-editor-rt/assets/119478320/9e8af21b-8f77-4800-b01e-7b6806a8cbd8)
我的写法是
<img width="536" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/119478320/d01597d1-9cde-4a7e-9c06-3db99d9e1e61">

### Procedure version

node：v20.10.0。 插件版本  "md-editor-rt": "^4.10.0",

**Comment by imzbf** [comment]
注意看文档哦，`callback`入参是数组
