### ISSUE TITLE
./node_modules/md-editor-rt/lib/es/chunks/Editor.mjs:2985:8 Module not found

### ISSUE THREAD

**Issue by GVALFER** [imzbf/md-editor-rt#132]
### 描述这个Bug

Hi

How can i fix it? 

- "next": "^14.1.0",
- npm run dev --turbo

I get this bug: ./node_modules/md-editor-rt/lib/es/chunks/Editor.mjs:2985:8 Module not found
-----------------

```javascript
./node_modules/md-editor-rt/lib/es/chunks/Editor.mjs:2985:8
Module not found
  2983 |       const $ = (o == null ? void 0 : o.js) || Cn;
  2984 |       if (/\.mjs/.test($))
> 2985 |         import(
       |         ^^^^^^^
> 2986 |           /* @vite-ignore */
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2987 |           /* webpackIgnore: true */
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2988 |           $
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2989 |         ).then((g) => {
       | ^^^^^^^^^^
  2990 |           a.current = g.default, s();
  2991 |         });
  2992 |       else {

https://nextjs.org/docs/messages/module-not-found```



### 版本号

^4.11.2

### 问题重现链接

_No response_

**Comment by imzbf** [comment]
install `mermaid`

```js
import mermaid from 'mermaid';
import { config } from 'md-editor-rt';

config({
  editorExtensions: {
    mermaid: {
      instance: mermaid
    }
  }
});
```

**Comment by CesGalaxy** [comment]
I still have the same error, I've already tried to:

- Install mermaid
- Add mermaid to config()
- Adding noMermaid to MdEditor

I'm using nextjs 14 and the latest version of md-editor-rt

**Comment by imzbf** [comment]
> I still have the same error, I've already tried to:
> 
> * Install mermaid
> * Add mermaid to config()
> * Adding noMermaid to MdEditor
> 
> I'm using nextjs 14 and the latest version of md-editor-rt

Could you provide a working project example?
