### ISSUE TITLE
Dynamic import error

### ISSUE THREAD

**Issue by remidosol** [imzbf/md-editor-rt#133]
### Describe the issue

I'm using this package to render a NextJS page and print it through Gotenberg which uses Chromium.

<img width="760" alt="Screenshot 2024-02-28 at 17 43 25" src="https://github.com/imzbf/md-editor-rt/assets/35426059/f712b469-66f5-4a74-be5c-8889cc171fd7">

I got this error. How to resolve this problem?

### Procedure version

md-editor-rt: v4.2.0
next: v13.4.5
react: v18.2.0
node: v18.18.0
npm: v9.8.1

**Comment by imzbf** [comment]
Try installing and replacing them:

https://imzbf.github.io/md-editor-rt/en-US/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20Import%20All%20Library

**Comment by elifraydin** [comment]
It works, thanks!
