### ISSUE TITLE
Expo error

### ISSUE THREAD

**Issue by sujanChy00** [imzbf/md-editor-rt#134]
### Describe the issue

![Screenshot from 2024-03-01 17-08-37](https://github.com/imzbf/md-editor-rt/assets/108806520/89964a1e-b46c-4e23-a4c0-994ef37692e0)

can i use this for my expo project?

are there any solutions to make it work only on web 
i don't want this editor for android or ios 

### Procedure version

node: v20.11.0

**Comment by imzbf** [comment]
Sorry, I haven't tried expo before.

But, the following can solve the errors on the image:

```js
import { config } from 'md-editor-rt';
import mermaid from 'mermaid';

config({
  editorExtensions: {
    mermaid: {
      instance: mermaid
    }
  }
});
```
