### ISSUE TITLE
渲染后提示未设置 key 值

### ISSUE THREAD

**Issue by Mingcomity** [imzbf/md-editor-rt#139]
### 描述这个Bug

在Next.js中，使用的Page Router，出现如下的错误
client.js:26 Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
![image](https://github.com/imzbf/md-editor-rt/assets/107565965/18b265c3-0029-4f01-be97-c42e9304befb)

### 版本号

NodeV21.6.2  md-editor-rt@4.12.2

**Comment by imzbf** [comment]
给它设置好key久可以了呀

**Comment by Mingcomity** [comment]
> 给它设置好钥匙久就可以了呀

![image](https://github.com/imzbf/md-editor-rt/assets/107565965/60474521-96f8-4268-9fcd-cf8b181ef091)
具体看报错不是我这边的问题，可以查看下面这个压缩包里简单化的示例，
[demo-md-editor.zip](https://github.com/imzbf/md-editor-rt/files/14759496/demo-md-editor.zip)

**Comment by imzbf** [comment]
4.12.3修复了
