### ISSUE TITLE
The `id` attribute is removed from source markup

### ISSUE THREAD

**Issue by Ibadichan** [imzbf/md-editor-rt#142]
### Describe the issue

```md
<section id="intro">

### Introduction

We provide an API that allows you to automate the process and integrate your software with our service.
...
</section>
```

Will produce html without `id` attr for section: `<section>...</section>`

### Procedure version

md-editor-rt@4.12.3

**Comment by imzbf** [comment]
Reference: https://imzbf.github.io/md-editor-rt/en-US/demo#%F0%9F%94%92%20Compile-time%20Prevention%20of%20XSS
