### ISSUE TITLE
Toolbar items insert the format sequences twice

### ISSUE THREAD

**Issue by bkosm** [imzbf/md-editor-rt#144]
### Describe the issue

Hi @imzbf, I have an issue while using this editor in `nextjs`. Whenever I use a toolbar item it seems to insert extra characters that break the markdown.

https://github.com/imzbf/md-editor-rt/assets/45885942/cdae1876-18a4-4784-a184-48d7001f8ec5

```tsx
"use client"

import { MdEditor } from "md-editor-rt"
import { useTheme } from "next-themes"

import "md-editor-rt/lib/style.css"
import { useState } from "react"

export function Editor() {
	const { theme } = useTheme()
	const [text, setText] = useState("")

	return (
		<MdEditor
			theme={theme === "light" ? "light" : "dark"}
			modelValue={text}
			language="en-US"
			onChange={(value) => setText(value)}
		/>
	)
}
```

### Procedure version

editor: 4.12.4, nextjs: 14.1.0

**Comment by imzbf** [comment]
I fixed it in the beta version.

```
npm i md-editor-rt@beta
```

And you can also set a fixed `editorId` to circumvent this issue.

**Comment by imzbf** [comment]
The latest version has been released
