### ISSUE TITLE
@codemirror异常

### ISSUE THREAD

**Issue by Memoyu** [imzbf/md-editor-rt#145]
### 描述这个Bug

![image](https://github.com/imzbf/md-editor-rt/assets/33112476/ee1b2b9f-772f-4326-8044-9f721798093b)
升级到4.13.0后，出现如图异常

### 版本号

4.13.0

**Comment by imzbf** [comment]
删除lock文件重新安装，或者先uninstall这个组件，然后再重新安装组件
