### ISSUE TITLE
How to configure editor to allow inserted html attributes and styles without stripping them off before rendering

### ISSUE THREAD

**Issue by techfortified** [imzbf/md-editor-rt#147]
### Describe the issue

First of all, thank you for this wonderful library. You've done a wonderful job.

I aim to insert HTML strings manually and dynamically within my content in md-editor-rt. This could involve adding advertisements and custom components between my content dynamically, which I have already managed.

for example

```js    
    const insertAdvert = () => {
    try {
      const htmlContent = `<div style="color:red;"><div class="style1">Hello world</div></div>` //getDynamicContent()
      editorRef.current?.insert((textContent) => {
      return {
        targetValue: `${htmlContent}`,
        select: true,
        deviationStart: 0,
        deviationEnd: 0
      };
    });
   }
}
  ```
  
  The example above works but the class `class1` and style `color:red`  got stripped when the html is rendered.
  
  I want to keep my custom classes and attributes to apply the styles that i want in a separate stylesheet.
  
  Please help, how can i configure the editor to retain or allow custom styles and all provided attributes?
  
  I'm using it in Nextjs blog application.

### Procedure version

"md-editor-rt": "^4.13.3"

**Comment by imzbf** [comment]
Perhaps this example can help you
https://imzbf.github.io/md-editor-rt/en-US/demo#%F0%9F%94%8F%20Modify%20XSS%20configuration
