### ISSUE TITLE
umi中使用个别语法预览存在问题

### ISSUE THREAD

**Issue by WhileSun** [imzbf/md-editor-rt#15]
![image](https://user-images.githubusercontent.com/31122836/156173262-2f6a3f07-0981-4323-a378-d28d7c3ce7a5.png)
这二种语法不识别

**Comment by imzbf** [comment]
列表没有序号是因为你的UI库定义了不显示`li`标签的`list-style`，没猜错的话是`antd`干的，它这个强制的样式被吐槽过，但是大家还是接受了。后面更新一个编辑器的默认标签样式出来。

**Comment by WhileSun** [comment]
感谢，确实UI导致的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imzbf/md-editor-rt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 晚上10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imzbf/md-editor-rt] umi中使用个别语法预览存在问题 (Issue #15)





 
列表没有序号是因为你的UI库定义了不显示li标签的list-style，没猜错的话是antd干的，它这个强制的样式被吐槽过，但是大家还是接受了。后面更新一个编辑器的默认标签样式出来。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by imzbf** [comment]
v1.6.0相对优化了该问题~
