### ISSUE TITLE
Nested list feature is not working any more that was fixed in v4.2.2

### ISSUE THREAD

**Issue by Udayendu** [imzbf/md-editor-rt#150]
### Describe the issue

As mentioned https://github.com/imzbf/md-editor-rt/issues/88, you fixed the nested list in v4.2.2 but thats not working any more with latest version 4.13.4. Please fix that.

### Procedure version

4.13.4

**Comment by imzbf** [comment]
fixed in 4.13.5

**Comment by Udayendu** [comment]
> fixed in 4.13.5

Yes, its working now. Thank you for the quick fix.
