### ISSUE TITLE
Table is not working after upgrading to the new version

### ISSUE THREAD

**Issue by Udayendu** [imzbf/md-editor-rt#152]
### Issue
Table has stopped working after upgrading to the new version and its generating the following error in the console.

```
replace monitor event exception！ RangeError: Selection points outside of document
    at checkSelection (index.js:1519:1)
    at new Transaction (index.js:2214:1)
    at Transaction.create (index.js:2221:1)
    at resolveTransaction (index.js:2385:1)
    at EditorState.update (index.js:2542:1)
    at EditorView.dispatch (index.js:7108:1)
    at Mr.replaceSelectedText (Editor.mjs:2354:1)
    at d (Editor.mjs:3052:1)
    at index.mjs:36:1
    at Array.forEach (<anonymous>)
```

### Procedure version

4.13.5

**Comment by imzbf** [comment]
Try reinstalling after uninstallation. If it still doesn't work, please provide an environment for restoring the issue

**Comment by Udayendu** [comment]
> Try reinstalling after uninstallation. If it still doesn't work, please provide an environment for restoring the issue

Its working after un-install and reinstall. 

As mentioned in https://imzbf.github.io/md-editor-rt/en-US/docs#📅%20tableShape, the table size has been capped at [6,4]. Can we grow it dynamically based on the move move when the table is open ??

**Comment by imzbf** [comment]
Not right now, I'll try it out

**Comment by Udayendu** [comment]
> Not right now, I'll try it out

Okay. Do you want me to open a new feature request for the same or you want to continue with this issue id ?

**Comment by imzbf** [comment]
try the beta version

```shell
npm i md-editor-rt@beta
```

docs: go to https://github.com/imzbf/md-editor-rt/tree/feature/4.14.0 and search for `tableShape`

**Comment by Udayendu** [comment]
> try the beta version
> 
> ```shell
> npm i md-editor-rt@beta
> ```
> 
> docs: go to https://github.com/imzbf/md-editor-rt/tree/feature/4.14.0 and search for `tableShape`

Hi @imzbf,

I have tested and it working fine. You can GA this code.

**Comment by imzbf** [comment]
4.14.0 Released
