### ISSUE TITLE
figcaption for images

### ISSUE THREAD

**Issue by Residenttt** [imzbf/md-editor-rt#154]
### A great idea

As seen in the picture, the image tag is added into the figure tag, but when I want to write a figcaption, there is no option I can do, I wonder if there is a way to add it or  would you consider adding it?

![image](https://github.com/imzbf/md-editor-rt/assets/25644243/367813a4-71d4-40ba-87c9-106e665f44a2)

**Comment by imzbf** [comment]
Perhaps you can disable the expansion of images and then allow the use of figcaption related tags.

The relevant documentation can be found here

https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%8D%A4%20markdownItPlugins
https://imzbf.github.io/md-editor-rt/en-US/demo#%F0%9F%94%8F%20Modify%20XSS%20configuration

**Comment by Residenttt** [comment]
Thanks for your advice.
