### ISSUE TITLE
How do you pre-transform HTML for preview?

### ISSUE THREAD

**Issue by nbelyh** [imzbf/md-editor-rt#155]
More of a question, but maybe a feature request.

I have some placeholders in the markdown, and would like them replaced in the preview. Example:

```
Hello, {{SomeName}}

Welcome to ...
If you have any questions, please reach us at {{email}}
```

In the preview, I want to see:

Hello, **John Doe**

Welcome to ...
If you have any questions, please reach us at **someone@somewhere.com**

Is it possible to pre-transform HTML **before it is rendered by the editor's preview**?

**Comment by nbelyh** [comment]
@imzbf  thank you for quick response!!

But not quite sure what do you mean? 
I thought of using the editor as a template editor (i.e. to edit the templates, containing parameters)
But in the preview, I would like to see some "sample" data, like above

**Comment by imzbf** [comment]
Sorry, there is no similar interface here.

And I am using a simple template replacement

https://github.com/imzbf/md-editor-rt/blob/dev-docs/public/demo-en-US.md#-cdn
https://github.com/imzbf/md-editor-rt/blob/dev-docs/src/pages/Demo/index.tsx#L20
