### ISSUE TITLE
Print button

### ISSUE THREAD

**Issue by mvallebr** [imzbf/md-editor-rt#159]
### A great idea

Hi - thanks for this fantastic component - I am using it in my MVP and I switched from a similar one, yours is the most complete one I found in the market.

I want to request a feature - although I can do it myself in my app outside of the component, it would be great to add to the toolbar a "print" button. I am not sure on how to implement it, but I don't think it would be a problem adding something like [react-to-print](https://www.npmjs.com/package/react-to-print) as dependency. 

This is more relevant when viewing a document, although I would still find it useful when editing a document. 

It would also be very useful to be able to have a print button outside of the component and call the print method of the component using a ref. This is not available for the full screen ability and I think it should, in my app it makes more sense for the button to be outside.

**Comment by imzbf** [comment]
Thanks for your support, based on your description, I think what you need is this extension: https://github.com/imzbf/md-editor-extension/tree/develop/packages/rt/components/ExportPDF

**Comment by mvallebr** [comment]
But I don't want to export to PDF, I want to send it to my printer.

**Comment by imzbf** [comment]
In the pop-up window of the browser, you can choose your own printer.
<img width="1141" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/37092006/d940eac2-841b-4f4a-81a6-585619536eb7">

**Comment by mvallebr** [comment]
Oh, I didn't know that was possible, in this case, yes, it seems to be what I want!
Thank you!

What about the print button being outside of the component - also the fullscreen button - is this something doable?

**Comment by imzbf** [comment]
No, the editor component actively injects generic properties into the extension.
