### ISSUE TITLE
希望预览模式下会支持导航栏

### ISSUE THREAD

**Issue by sansheng741** [imzbf/md-editor-rt#16]

**Comment by imzbf** [comment]
下个版本就支持了，目前已经在vue版本上使用上了。

**Comment by sansheng741** [comment]
好的，期待

**Comment by imzbf** [comment]
v1.6.0已发布，内部的Catalog供外部使用，请参考[文档](https://imzbf.github.io/md-editor-rt/docs#%F0%9F%90%BB%20Catalogue)
