### ISSUE TITLE
VM16113:10 TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by ihezebin** [imzbf/md-editor-rt#160]
### 描述这个Bug

只添加了编辑器

<img width="466" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/36706912/372f1dfe-c762-40ca-979b-7c96e02ec731">

 <MdEditor
        modelValue={content}
        onChange={setContent}
        onSave={(content) => console.log(content)}
      />

VM16113:10 TypeError: Cannot read properties of undefined (reading 'map')
    at Object.toJSON (index.js:249:1)
    at JSON.stringify (<anonymous>)
    at Object.parseData (<anonymous>:8:116)
    at <anonymous>:10:2186
    at Array.reduce (<anonymous>)
    at <anonymous>:10:2114
    at i (<anonymous>:10:2706)
    at <anonymous>:10:2993
    at _ (<anonymous>:10:3119)
    at <anonymous>:10:3363

### 版本号

4.15.0

**Comment by imzbf** [comment]
方便的话提供下问题重现链接或者问题重现的最简项目

**Comment by ihezebin** [comment]
https://gitee.com/hezebin-react/test.git

**Comment by imzbf** [comment]
运行你的项目没有发现这个提示，是否还有必要的操作？

> https://gitee.com/hezebin-react/test.git

**Comment by ihezebin** [comment]
啊，这么神奇，目前测试项目和正式使用都没这个报错了
