### ISSUE TITLE
目前图片语法并不支持设置图片大小

### ISSUE THREAD

**Issue by ihezebin** [imzbf/md-editor-rt#161]
### 一个很棒的想法

typora 支持类似这样的语法来设置原图的显示尺寸
```markdown
<img src="/Users/hezebin/Documents/test.png" alt="后风窗" style="zoom:25%;" />
```

**Comment by ihezebin** [comment]
我的问题似乎更像是支持的 HTML 语法中的 style 在转换渲染后丢失了
<img width="1439" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/36706912/8d8feb74-16f7-4c32-a30a-33b348dffaf2">

**Comment by ihezebin** [comment]
另外目前的最新 tag 中缺少一个你官网中的主题 ：arknights

<img width="1431" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/36706912/825803ba-b7ce-4b72-8473-abd3b395fbe6">

**Comment by imzbf** [comment]
1. 是因为内置了xss组件，你可以考虑移除xss组件或者添加你想要支持的属性和标签，参考：https://imzbf.github.io/md-editor-rt/zh-CN/demo#%F0%9F%94%8F%20%E4%BF%AE%E6%94%B9%20xss%20%E9%85%8D%E7%BD%AE
2. arknights没有在编辑器中内置，是这个项目里面的：https://github.com/imzbf/md-editor-extension
