### ISSUE TITLE
How to allow event on elements?

### ISSUE THREAD

**Issue by techfortified** [imzbf/md-editor-rt#162]
### Describe the issue

I have a custom element where I set event listener to detect when the element is clicked in the browser but it seems the event gets stripped off.

`<button onclick="myFunction()">Click me</button>`

Please how can I make it work?

### Procedure version

"md-editor-rt": "^4.13.3"

**Comment by imzbf** [comment]
You need to disable or modify the xss extension：https://imzbf.github.io/md-editor-rt/en-US/demo#%F0%9F%94%8F%20Modify%20XSS%20configuration

And `extendedWhiteList` is not supported in `4.13.3`, you need to use annotated examples.
