### ISSUE TITLE
是否对chrome的版本有要求

### ISSUE THREAD

**Issue by QiaoLi1996** [imzbf/md-editor-rt#163]
### Describe the issue

用户的chrome版本太低，chrome在75版本，无法正常加载，但是用户切换到edge使用也正常。
后来让用户更新chrome到最新的版本使用正常

### Procedure version

react_17 + mui_V4 + webpack5(module feduration)

**Comment by QiaoLi1996** [comment]
本地测试将chrome降低版本到75，确实无法加载。
想要知道不同Browser对应的最低版本要求

**Comment by imzbf** [comment]
1. 最低浏览器版本暂时提供不了，后面我会标识在文档中
2. 参考：https://imzbf.github.io/md-editor-rt/en-US/demo#%F0%9F%A4%93%20CDN
3. 适配方法需要找到内部依赖是否能够被babel向后兼容，最理想的是提示用户升级

**Comment by imzbf** [comment]
75版本是因为不支持`??`的用法，使用`@babel/plugin-transform-nullish-coalescing-operator`转换一下

**Comment by QiaoLi1996** [comment]
Problem：
这个问题困扰我有一阵子了，一开始尝试webpack resolve中alias到umd/index.js，但未能配置成功
后来发现75版本确实不支持??和?.   

1)尝试用了`@babel/plugin-transform-nullish-coalescing-operator`和`@babel/plugin-transform-optional-chaining`，本地webpack打包的时候可以成功，`??`和`?. `都能解决；
但是我用jenkins部署server的时候，`??`能转换成功，`?.`一直不可以
local `nodejs 18.20.2/20.11.1`(success)     
![image](https://github.com/imzbf/md-editor-rt/assets/73815759/78603fe0-4c55-4c48-8073-381fd2cc4f07)
  
jenkins `nodejs 18.20.2`(fail)
![image](https://github.com/imzbf/md-editor-rt/assets/73815759/2c550e99-9f7b-47fe-a672-b8519c2dab8b)

当然我们也在敦促用户升级chrome 版本，不过也希望找到原因并解决问题
有人能帮忙提供更多的帮助吗  不过不限于提供兼容的版本  任何的建议或者想法都很感激

**Comment by QiaoLi1996** [comment]
> @imzbf   
   Problem： 这个问题困扰我有一阵子了，一开始尝试webpack resolve中alias到umd/index.js，但未能配置成功 后来发现75版本确实不支持??和?.
> 
> 1)尝试用了`@babel/plugin-transform-nullish-coalescing-operator`和`@babel/plugin-transform-optional-chaining`，本地webpack打包的时候可以成功，`??`和`?. `都能解决； 但是我用jenkins部署server的时候，`??`能转换成功，`?.`一直不可以 local `nodejs 18.20.2/20.11.1`(success) 
![image](https://private-user-images.githubusercontent.com/73815759/337572005-78603fe0-4c55-4c48-8073-381fd2cc4f07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDY5MTAsIm5iZiI6MTcxNzc0NjYxMCwicGF0aCI6Ii83MzgxNTc1OS8zMzc1NzIwMDUtNzg2MDNmZTAtNGM1NS00YzQ4LTgwNzMtMzgxZmQyY2M0ZjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA3NTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MjUzMDQ1MWQ1Yjg5Y2Y2ZTA2NzE0OWY1MDVjNTNjNTIzYWRkMzY0MWJhMDYwYzczZjdmN2VmNmE4OTNkYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._6MooZQBw1v0VM39HrHNxzVogGr0B-YglUuhb2j7x3A)
> 
> jenkins `nodejs 18.20.2`(fail)
 ![image](https://private-user-images.githubusercontent.com/73815759/337573276-2c550e99-9f7b-47fe-a672-b8519c2dab8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDY5MTAsIm5iZiI6MTcxNzc0NjYxMCwicGF0aCI6Ii83MzgxNTc1OS8zMzc1NzMyNzYtMmM1NTBlOTktOWY3Yi00N2ZlLWE2NzItYjg1MTljMmRhYjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA3NTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MTFkNmNlYjRhMDM2OGVkOWFmNjNkNjRhMDBjYWViZjRlZTNhM2I4YjljOWQ1OGNlOWM2ZjdiMTJmYzkwNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1URs0uactMx3VKdEachgB-UZZ04WBlS2csCHUoFUuk)
> 
> 能帮忙提供更多的帮助吗？ 包括不限于提供兼容的版本，任何的建议或者想法都很感激！
    我们也在敦促用户升级chrome 版本，不过也希望找到原因并解决问题 。




> 75版本是因为不支持`??`的用法，使用`@babel/plugin-transform-nullish-coalescing-operator`转换一下

**Comment by QiaoLi1996** [comment]
进一步研究发现：
   并不是`@babel/plugin-transform-nullish-coalescing-operator`和`@babel/plugin-transform-optional-chaining`生效，而是` presets: [ ['@babel/preset-env', { targets: { chrome: 68, edge: 79 } }] ]`  起了作用，
![image](https://github.com/imzbf/md-editor-rt/assets/73815759/3d35e772-3be7-4880-89bc-3d753205e827)

但我还是不能理解为什么  
1）本地webpack打包的时候`??`和`?. `都能解决 ； jenkins部署server   只有`??`能解决，`?.`却存在问题
2）此外我在改项目里针对tsx文件有类似的配置；但是tsx完全没问题，mjs文件却存在这种不一致的问题
![image](https://github.com/imzbf/md-editor-rt/assets/73815759/a711efd6-5d89-4061-914c-045ec45b265d)


resolve.extensions这边也配置了:
`
    resolve: {
      alias: {
        ...alias,
        axcore: path.resolve('./node_modules/axcore'),
        api: path.resolve('./src/api')
      },
      extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.json'],
      fallback: { crypto: false }
    },
`
难道还缺少什么？

**Comment by QiaoLi1996** [comment]
已经解决，thanks~
