### ISSUE TITLE
编辑区与预览区滚动位置不同步

### ISSUE THREAD

**Issue by liu-DR** [imzbf/md-editor-rt#165]
### Describe the issue

![image](https://github.com/imzbf/md-editor-rt/assets/87759649/172008f5-a4cf-4a1b-9237-9cffb855d89f)
当左侧编辑区出现滚动条时，修改编辑区内容，预览区未定位在修改内容的位置
滚动的定位是否可以根据编辑区域聚焦位置来定位

### Procedure version

vscode

**Comment by liu-DR** [comment]
node_version：18.20.0

**Comment by liu-DR** [comment]
node_version：18.20.0

**Comment by imzbf** [comment]
方便的话，提供一下出现这种情况的内容，或者替换一下隐私内容

**Comment by liu-DR** [comment]
![Uploading Snipaste_2024-06-28_14-28-50.png…]()

当内容中出现图片过多时，编辑区滚动到底部时，右侧预览区滚动位置并未同步，并且在编辑区底部编辑内容时，预览区的位置会向上发生滚动，导致无法显示底部添加的内容，具体情况再官网home处的例子可以完美复现

**Comment by imzbf** [comment]
滚动做了节流，不能保证每次滚动都能够同步，时间区间有1ms，所以有时候滚动到底部不同步没有一点点小的偏差是正常的。减慢滚动的速度通常能够完全同步。


关于输入后会有一点点上移的迹象，也是这个原因，目前还没有很好的解决方案。

另外关于你的两个图上的示例，左侧均有部分剩余空间才到达底部，这时是通过判断当前左右侧顶部的可视行到底部的距离，按比例同步了来实现完全到底部时，不会因为图片等相关内容，导致左侧到底部，而右侧差了很大一截。相关的同步功能在4.16.x-4.17.0过程中逐步优化了。

**Comment by liu-DR** [comment]
噢噢噢，好的呢
