### ISSUE TITLE
Add `textareaRef` prop to `<MdEditor/>`

### ISSUE THREAD

**Issue by Ibadichan** [imzbf/md-editor-rt#166]
### A great idea

Can you add `textareaRef: func | reactRef` prop to `<MdEditor/>`?
I am using `react-hook-form` for form validation and i need to pass input ref to the textarea in order to focus textarea after form submit (if field is invalid).

**Comment by imzbf** [comment]
This could be useful; I will make a decision after delving into the workings of this library.

**Comment by imzbf** [comment]
I tried to use this lib. Except that the border highlighting needs to be adapted by myself, we can use the existing API to focus textarea:

https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%8E%AF%20focus
