### ISSUE TITLE
Custom Component Embed

### ISSUE THREAD

**Issue by abanseka** [imzbf/md-editor-rt#169]
### A great idea

Hi @imzbf,
First of all awesome editor you've put together here. thank you very much.
I'd like to request support for embedding custom components into the editor.
for example. rendering a video player within the editor, as well as image content. not just links but the actual preview of this content.

if the editor already supports these features.
where can I find this in the docs? please :pray: 

> Again great editor you've put together here. hoping to read from you.

**Comment by imzbf** [comment]
If you're referring to a React component, this cannot be done. However, if it's regular HTML, it is possible. For example, if you want to watch a YouTube video within a document, you can directly embed the code.

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/czTpTKvv68I?si=9JHSDRlYc3Hffnbb" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
```

**Comment by abanseka** [comment]
ah ok.
thanks for the clarification @imzbf :pray:
