### ISSUE TITLE
"md-editor-rt": "^1.6.0",  目录无法显示

### ISSUE THREAD

**Issue by sansheng741** [imzbf/md-editor-rt#17]
![image](https://user-images.githubusercontent.com/38903744/157658850-5cc3fa28-d2af-46d2-ba29-94368f30e14d.png)

`import React from 'react'
import Editor from 'md-editor-rt'
import 'md-editor-rt/lib/style.css'

export type ArticleProps = {
  text?: string;
};

const Article: React.FC<ArticleProps> = (props) => {
  const {text} = props
  const editorId = 'my-editor'
  return (
    <>
      <Editor theme={'light'} editorId={editorId} modelValue={text} previewOnly={true} showCodeRowNumber={true}/>
      <Editor.Catalog editorId={editorId}/>
    </>
  )
}

export default Article
`

**Comment by imzbf** [comment]
我试试还原这个问题，在文档项目中和nextjs中多没有出现。这可能是监听事件触发先后问题导致的。

**Comment by sansheng741** [comment]
我的是Umijs + antd pro

**Comment by imzbf** [comment]
v1.6.1版本优化了该问题，试试看
