### ISSUE TITLE
标题输入中文时尾部会多一个字符，正文没问题

### ISSUE THREAD

**Issue by ihezebin** [imzbf/md-editor-rt#170]
### 描述这个Bug

https://github.com/user-attachments/assets/67edfa64-bc9b-489b-9823-d32bec4994fc

示例代码仓库：https://gitee.com/ihezebin/temp-test.git

node版本：<img width="272" alt="image" src="https://github.com/user-attachments/assets/ec6fd059-b200-4d3d-b0ef-0cc439eea903">

谷歌浏览器版本：版本 127.0.6533.100（正式版本） (arm64)

目前发现 谷歌和 edge 存在，火狐和 safari 不存在。且在一个新的 React 项目中使用，也没问题，单纯在这个项目中存在，很奇怪。

### 版本号

"md-editor-rt": "^4.18.1"

### 问题重现链接

https://gitee.com/ihezebin/temp-test.git

**Comment by imzbf** [comment]
codemirror正在使用chromium新特性，参考这个[issue](https://github.com/imzbf/md-editor-v3/issues/589)，这个问题在4.17.4中已修改，老项目删除lock文件或者先uninstall后再install
