### ISSUE TITLE
Nextjs 15 with turbo has build issue after  use this package

### ISSUE THREAD

**Issue by slim-fighting** [imzbf/md-editor-rt#171]
### Describe the issue

我用测试版的nextjs15以及turbo 构建的项目build报错了
![屏幕截图 2024-08-17 024625](https://github.com/user-attachments/assets/792413da-3da9-40ab-9dcf-21aab8957711)

### Procedure version

node20.9.0

**Comment by slim-fighting** [comment]
turboPack有动态导入的bug。。。[issue](https://github.com/vercel/next.js/issues/61180)

**Comment by imzbf** [comment]
跳过动态导入，使用 npm install安装mermaid，然后通过config配置
