### ISSUE TITLE
How to replace the dependency library cdn url?

### ISSUE THREAD

**Issue by noMoreEver** [imzbf/md-editor-rt#173]
### Describe the issue

Hello. I'm using this excellent library for making a private note-taking website. And i found out this library will **fetch some dependency librarys from cdn**. I want to **replace these urls to my server urls**. I read through the README but can't get a solution. 
Would you give me some advices? thank you very much. 

![image](https://github.com/user-attachments/assets/99da03de-6478-473e-9e53-a4b1a1949beb)

### Procedure version

vite and react-18.3.1, md-editor-rt-4.18.1

**Comment by imzbf** [comment]
The example is here

https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%A5%A0%20editorExtensions

**Comment by noMoreEver** [comment]
> The example is here
> 
> https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%A5%A0%20editorExtensions

it works, thank you very much.
