### ISSUE TITLE
仅预览和编辑模式切换时编辑器有闪烁

### ISSUE THREAD

**Issue by itforce-liyan** [imzbf/md-editor-rt#174]
### Describe the issue

从仅预览切换回编辑模式，会出现闪烁。
![微信截图_20240828145307](https://github.com/user-attachments/assets/94b7ec49-1f3a-4da2-a9fc-71ffb531f957)

反复点击 `仅预览` 按钮可以复现。

### Procedure version

md-editor-rt version: 4.18.0

**Comment by imzbf** [comment]
https://github.com/user-attachments/assets/bf29a677-5f1d-4ddb-bab5-cd3a8e3c1404

是否还有其他操作？

**Comment by itforce-liyan** [comment]
Sorry,漏了一步。

1. 编辑模式先关闭 `预览`，小眼睛按钮；
2. 反复点击 `仅预览` 按钮；


https://github.com/user-attachments/assets/d2b0a485-b827-4ad0-a897-f8d3beb03a12

**Comment by imzbf** [comment]
4.20.0修复了该问题
