### ISSUE TITLE
希望新增一个协同编辑功能

### ISSUE THREAD

**Issue by han201379873** [imzbf/md-editor-rt#178]
### 一个很棒的想法

连接用一个ws链接，根据不同的内容和编辑试试显示每个协同编辑的状态

**Comment by imzbf** [comment]
这个功能在这里 https://github.com/imzbf/md-editor-v3/issues/61 提过，但是实现有些偏离了`markdown`编辑器的方向。建议有需要克隆源码单独尝试。
在下个版本中支持获取到codemirror示例，也许可以通过它来实现。

后续有方案会提供demo。

**Comment by imzbf** [comment]
这里有一个基础demo，你可以通过这种方式实现

```
npm i y-codemirror.next yjs y-webrtc
```

main.js

```js
import { config } from 'md-editor-v3';

const text = ref('');
const editor = ref<ExposeParam>();

import * as Y from 'yjs';
// @ts-ignore
import { yCollab } from 'y-codemirror.next';
import { WebrtcProvider } from 'y-webrtc';

import * as random from 'lib0/random';

const usercolors = [
  { color: '#30bced', light: '#30bced33' },
  { color: '#6eeb83', light: '#6eeb8333' },
  { color: '#ffbc42', light: '#ffbc4233' },
  { color: '#ecd444', light: '#ecd44433' },
  { color: '#ee6352', light: '#ee635233' },
  { color: '#9ac2c9', light: '#9ac2c933' },
  { color: '#8acb88', light: '#8acb8833' },
  { color: '#1be7ff', light: '#1be7ff33' },
];

// select a random color for this user
const userColor = usercolors[random.uint32() % usercolors.length];

const ydoc = new Y.Doc();
const provider = new WebrtcProvider('codemirror6-demo-room', ydoc);
const ytext = ydoc.getText('codemirror');

const undoManager = new Y.UndoManager(ytext);

provider.awareness.setLocalStateField('user', {
  name: 'Anonymous ' + Math.floor(Math.random() * 100),
  color: userColor.color,
  colorLight: userColor.light,
});

config({
  codeMirrorExtensions(_theme, extensions) {
    return [...extensions, yCollab(ytext, provider.awareness, { undoManager })];
  },
});
```

**Comment by imzbf** [comment]
完整示例：https://imzbf.github.io/md-editor-rt/en-US/demo#%F0%9F%8E%B3%20co-working

**Comment by mingchiuli** [comment]
> 这里有一个基础demo，你可以通过这种方式实现
> 
> ```
> npm i y-codemirror.next yjs y-webrtc
> ```
> 
> main.js
> 
> import { config } from 'md-editor-v3';
> 
> const text = ref('');
> const editor = ref<ExposeParam>();
> 
> import * as Y from 'yjs';
> // @ts-ignore
> import { yCollab } from 'y-codemirror.next';
> import { WebrtcProvider } from 'y-webrtc';
> 
> import * as random from 'lib0/random';
> 
> const usercolors = [
>   { color: '#30bced', light: '#30bced33' },
>   { color: '#6eeb83', light: '#6eeb8333' },
>   { color: '#ffbc42', light: '#ffbc4233' },
>   { color: '#ecd444', light: '#ecd44433' },
>   { color: '#ee6352', light: '#ee635233' },
>   { color: '#9ac2c9', light: '#9ac2c933' },
>   { color: '#8acb88', light: '#8acb8833' },
>   { color: '#1be7ff', light: '#1be7ff33' },
> ];
> 
> // select a random color for this user
> const userColor = usercolors[random.uint32() % usercolors.length];
> 
> const ydoc = new Y.Doc();
> const provider = new WebrtcProvider('codemirror6-demo-room', ydoc);
> const ytext = ydoc.getText('codemirror');
> 
> const undoManager = new Y.UndoManager(ytext);
> 
> provider.awareness.setLocalStateField('user', {
>   name: 'Anonymous ' + Math.floor(Math.random() * 100),
>   color: userColor.color,
>   colorLight: userColor.light,
> });
> 
> config({
>   codeMirrorExtensions(_theme, extensions) {
>     return [...extensions, yCollab(ytext, provider.awareness, { undoManager })];
>   },
> });

这个案例用起来问题还是挺多的，比如这个设置把房间号写死了，实际上房间号需要进入组件才能确定，但是本编辑器并不推荐这样去配置。我在实际网络环境里用时灵时不灵
