### ISSUE TITLE
表格支持合并问题

### ISSUE THREAD

**Issue by quhongli123** [imzbf/md-editor-rt#185]
### 

<img width="925" alt="image" src="https://github.com/user-attachments/assets/2aa8deaf-049b-4f00-9f7c-8f96b1b87734">
想让表格支持动态合并拆分

**Comment by quhongli123** [comment]
> ### 
> <img alt="image" width="925" src="https://private-user-images.githubusercontent.com/102941594/384584403-2aa8deaf-049b-4f00-9f7c-8f96b1b87734.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzU4MjYsIm5iZiI6MTczMTEzNTUyNiwicGF0aCI6Ii8xMDI5NDE1OTQvMzg0NTg0NDAzLTJhYThkZWFmLTA0OWItNGYwMC05ZjdjLThmOTZiMWI4NzczNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwNjU4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjk5MTQ3OWVmZThlMjgwMmNhNTgxM2U2YjM0Y2U0OWNhMDE2Njk4OWI4Y2VkMWJhYzM3ZjJjNmFkMzcxYWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vTAVye95NV1UnKwcN7J-GVp4jUxCwSHpXwwig0cDwq4"> 想让表格支持动态合并拆分

**Comment by imzbf** [comment]
没有看到你的html中有合并单元格相关的设定？如果有但是预览中不存在的话，尝试禁用xss
