### ISSUE TITLE
图片希望支持调整大小或者拖拽缩放

### ISSUE THREAD

**Issue by Sole-BadGuy** [imzbf/md-editor-rt#187]
### 一个很棒的想法

图片能不能支持调整大小或者拖拽缩放，现在上传一张图片会跟原图保持一致的大小，但是又不希望去修改原图

**Comment by imzbf** [comment]
这个做不到，这个组件有别于富文本那种，无法给它们做调整的“手柄”，你可以使用这个扩展：https://github.com/imzbf/md-editor-extension/tree/develop/packages/rt/components/OriginalImg 去添加html标签语法的图片，或者自定义上传的工具栏，调整大小可以通过设置img的width和height去实现

**Comment by Sole-BadGuy** [comment]
> 这个做不到，这个组件有别于富文本那种，无法给它们做调整的“手柄”，你可以使用这个扩展：https://github.com/imzbf/md-editor-extension/tree/develop/packages/rt/components/OriginalImg 去添加html标签语法的图片，或者自定义上传的工具栏，调整大小可以通过设置img的width和height去实现

好的 我去试试  感谢回复！
