### ISSUE TITLE
MdEditorRT编辑器的工具栏有个save保存按钮，这个按钮怎么用

### ISSUE THREAD

**Issue by YB-win** [imzbf/md-editor-rt#189]
### Describe the issue

MdEditorRT编辑器的工具栏有个save保存按钮，这个按钮怎么用，是需要对接后端接口保存到后端吗？
我在官网首页试了试保存按钮似乎并没有实质效果，点击旁边的前进或后退  编辑器的内容还是会变化并没有保存。有没有能定位到这个save功能的具体链接或者代码文件内
![图片](https://github.com/user-attachments/assets/2ec65f99-f343-42b7-bdbc-eebe29de7a9a)

### Procedure version

v1

**Comment by imzbf** [comment]
它会触发onSave事件，至于能保存，是开发者自己定义的
