### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by FerretAngel** [imzbf/md-editor-rt#191]
### 描述这个Bug

![image](https://github.com/user-attachments/assets/c67dd799-ca28-42e1-b0d5-33f839e9c8ab)
![image](https://github.com/user-attachments/assets/080e6540-6e4e-455f-90c7-edca58ff3653)

### 版本号

		"md-editor-rt": "^5.0.2", 		"next": "14.2.4",

### 问题重现链接

http://115.159.96.202:36168/down/ntE6RKGikoZc.zip

**Comment by imzbf** [comment]
如果你的环境不支持动态导入，请参考：https://imzbf.github.io/md-editor-rt/zh-CN/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93

手动引入 mermaid

**Comment by FerretAngel** [comment]
> 如果你的环境不支持动态导入，请参考：https://imzbf.github.io/md-editor-rt/zh-CN/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93
> 
> 手动引入 mermaid

手动引入了，还是这个问题。
不知道我的操作对不对。next里面的入口文件应该是app/layout.tsx?
![image](https://github.com/user-attachments/assets/fc5d55d3-e1fd-4fc8-a365-f3b73d7c5447)

**Comment by imzbf** [comment]
这看起来是router模式，新版本好像支持的，你能不能给我一个你这个问题的基础项目我看看

**Comment by FerretAngel** [comment]
> 这看起来是router模式，新版本好像支持的，你能不能给我一个你这个问题的基础项目我看看
源码下载链接
http://115.159.96.202:36168/down/ntE6RKGikoZc.zip

**Comment by imzbf** [comment]
turbopack有问题，你可以考虑升级next到15，或者在dev命令后面移除--turbo

**Comment by FerretAngel** [comment]
> turbopack有问题，你可以考虑升级next到15，或者在dev命令后面移除--turbo

好的，谢谢你！

**Comment by FerretAngel** [comment]
> turbopack有问题，你可以考虑升级next到15，或者在dev命令后面移除--turbo

preview模块在ssr的时候也会报错。
![image](https://github.com/user-attachments/assets/5f26e0f0-f488-4227-a8be-cbeb71128358)
感觉next用的好心累啊，之前nuxt用着一点问题没有，嘎嘎好用。

**Comment by imzbf** [comment]
这个问题在demo中没有发现。

考虑用它旧的page模式吧，和nuxt一样，router模式感觉没优化好，像单页应用的公共导航，构建出来切换路由会重新加载。
