### ISSUE TITLE
theme 如果设置为dark，开始会有一段时间的空白

### ISSUE THREAD

**Issue by codexu** [imzbf/md-editor-rt#192]
### 描述这个Bug

组件渲染后，可以正常显示为黑色

### 版本号

5.0.2

**Comment by imzbf** [comment]
什么空白，详细描述一下

**Comment by codexu** [comment]
感谢回复，真抱歉，是我这边的问题，我是用的是 [next-themes(]https://www.npmjs.com/package/next-themes)，在取值时有延迟，导致的白屏，直接赋值 dark 是没问题的。
