### ISSUE TITLE
是否支持设置图片的大小和居中

### ISSUE THREAD

**Issue by YB-win** [imzbf/md-editor-rt#193]
### Describe the issue

![图片](https://github.com/user-attachments/assets/26c3fc88-b610-4978-8a79-77da812e7ffe)
我添加了这样一个图片链接，预览出来图片不是居中放置，而是在预览框的左边，是否支持设置图片的大小和居中位置呢？如何可以要怎么实现？另外官方文档展示的案例，右下角的时间是如何设置显示的。我没有找到相关接口属性
![图片](https://github.com/user-attachments/assets/de8a60b0-a730-4f73-9b0c-2a67f4f5e2a4)

### Procedure version

v1

**Comment by imzbf** [comment]
使用html的图片标签实现，markdown无法直接语法上设置样式

这是底部工具栏的示例：https://imzbf.github.io/md-editor-v3/zh-CN/api#%F0%9F%A6%BF%20defFooters
