### ISSUE TITLE
MdCatalog目录结构缓存之前的值

### ISSUE THREAD

**Issue by Sole-BadGuy** [imzbf/md-editor-rt#194]
### 描述这个Bug

当MdPreview的值从一个有目录结构切换到另一个没有目录结构的值是，当前的目录会显示上一个目录结构，注意是切换不是用户输入 你可以用官网的例子打开目录结构然后直接复制一个没有目录结构的数据进去 目录不会更新刷掉

### 版本号

4.0.0

**Comment by Sole-BadGuy** [comment]
![微信图片_20241212171019](https://github.com/user-attachments/assets/9a5f47f8-83f1-4319-b7c6-712c17b08bc0)

**Comment by imzbf** [comment]
图上的操作是直接输入，或者是粘贴？从左侧的代码上看没有上面描述的“切换”的过程。在文档的编辑器上无法通过输入来还原这个问题，我想知道出现这个问题的具体步骤，以便确定问题所在

**Comment by Sole-BadGuy** [comment]
![微信图片_20241213141509](https://github.com/user-attachments/assets/4b0bb757-6347-4e89-9193-72dc1b288cd9)
![微信图片_20241213141553](https://github.com/user-attachments/assets/62e6db4b-6847-42e9-9444-500813f82741)
其实跟输入没关系  感觉是滚动的原因  第一张是我的简单demo 里面故意加了固定高让它存在滚动条  然后 点击切换文本变为123
向下滚动一点后就会出现上一个的目录结构

**Comment by Sole-BadGuy** [comment]
import { Button } from "antd";
import { MdCatalog, MdEditor, MdPreview } from "md-editor-rt";
import "md-editor-rt/lib/style.css";
import { useState } from "react";

export default function App() {
  const [scrollElement] = useState(document.documentElement);
  const [text, setText] = useState(`## 😲 md-editor-rt
Markdown 编辑器，React 版本，使用 jsx 和 typescript 语法开发，支持切换主题、prettier 美化文本等。
### 🤖 基本演示
**加粗**，<u>下划线</u>，_斜体_，~~删除线~~，上标^26^，下标~1，[超链接](https://github.com/imzbf)`);

  return (
    <div style={{ height: "2200px", display:"flex" }}>
      <Button onClick={() => {
        setText(`123`)
      }}>切换</Button>
      <MdPreview
        editorId="md-editor-preview"
        modelValue={text}
      />
      <div style={{display:"flex",border:"1px"}}>
        <MdCatalog
          scrollElementOffsetTop={60}
          offsetTop={80}
          editorId="md-editor-preview"
          scrollElement={scrollElement}
        />
      </div>
    </div>
  );
}

**Comment by imzbf** [comment]
在5.1.1中优化了该问题
