### ISSUE TITLE
Next15渲染ol出错

### ISSUE THREAD

**Issue by YDKD** [imzbf/md-editor-rt#195]
### Describe the issue

我现在在Next15中使用，当渲染ol时会直接报错“ReferenceError: isSpace is not defined”；从报错信息来源来看，是来自于`markdown-it`库；我也尝试降级到Next14版本，降级后不会出现这个错误，不知道作者能否支持到Next15版本呢，万分感谢！

报错的代码应该是解析出错
例如：`const mdData = "1. 123"`就会出错，但是如果是这样 `const mdData = "1\\. 123"`，能成功渲染，但是渲染的就不是ol，而是p标签；

依赖版本：
`  "md-editor-rt": "^5.1.1",
    "next": "15.1.2",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"`

### Procedure version

nodejs

### Reproduction link

https://codesandbox.io/p/github/YDKD/next15-with-md-editor-rt/main?file=%2Fapp%2Fpage.tsx%3A8%2C6

**Comment by imzbf** [comment]
不使用turbopack就没问题

**Comment by YDKD** [comment]
> 不使用turbopack就没问题

好的，感谢

**Comment by liyu233** [comment]
> 不使用turbopack就没问题

我试了下，确实是。
nextjs15默认使用turbopack，所以楼上说的降级可以，因为14不是turbopack。
但暂时没查出具体原因。
