### ISSUE TITLE
多谢作者的付出，在此提几个建议！

### ISSUE THREAD

**Issue by windf17** [imzbf/md-editor-rt#2]
1. 左侧编辑区、右侧预览区，也可以只显示编辑区，但是没有只显示预览区的功能，建议加上只显示预览区不显示编辑区的按钮。
2. 建议Editor的prop参数里增加width和height的两项参数。

**Comment by imzbf** [comment]
感谢建议~

**Comment by imzbf** [comment]
> 1. 左侧编辑区、右侧预览区，也可以只显示编辑区，但是没有只显示预览区的功能，建议加上只显示预览区不显示编辑区的按钮。
> 2. 建议Editor的prop参数里增加width和height的两项参数。

- 关于仅显示预览区域，由于存在工具栏，会导致事件控制不一致，编辑器暂不支持这样做，需要只预览内容请使用`previewOnly`
- `width`相关设置，`v1.2.0`版本后可以通过`style`属性设置了。
