### ISSUE TITLE
在TSX里提示缺少属性

### ISSUE THREAD

**Issue by xiao-cao-x** [imzbf/md-editor-rt#21]
有些东西默认就行的,这样直接用会有警告
![image](https://user-images.githubusercontent.com/76673990/161935226-e1e995b0-13dc-499a-a71a-e0159521799b.png)

**Comment by imzbf** [comment]
这是`webstorm`的提示？这个组件预设了`defaultProps`，需要合理的设置`eslint`才能规避这种提示

**Comment by xiao-cao-x** [comment]
是IDEA

**Comment by imzbf** [comment]
可以忽略这个提示，内部有完善的`defaultProps`，idea没有正确的识别该属性。

**Comment by xiao-cao-x** [comment]
我尝试让他不提示这个

**Comment by imzbf** [comment]
在`2.x`版本后，咱们优化了这个提醒~
