### ISSUE TITLE
关于onUploadImg的类型问题

### ISSUE THREAD

**Issue by sniqa** [imzbf/md-editor-rt#22]
### [onUploadImg的第一个参数是FileList类型，点击上传图片的话函数传进来的是FileList类型，但是点击裁剪上传的话函数传进来的却是File[]类型:

![2022-04-23 121601](https://user-images.githubusercontent.com/56432490/164876118-4eb3cfc2-16e3-4060-ab91-7d47968fab60.png)
### 如果是使用FileList.item()而不是通过数组下标进行取值的话就会报错:
![屏幕截图 2022-04-23 122930](https://user-images.githubusercontent.com/56432490/164877129-4c8baff3-119e-4279-abac-5a01c3148e83.png)

**Comment by imzbf** [comment]
em..这个后面统一成返回`Array`，目前先使用`Array.from`规避这个问题

**Comment by imzbf** [comment]
在`1.6.12`统一了这个问题，先入参全部类型为数组文件类型
