### ISSUE TITLE
there's something wrong with cdn resource

### ISSUE THREAD

**Issue by ChineseBread** [imzbf/md-editor-rt#25]
cdn的资源全部挂掉了，我换了很多的网都拿不到，已经更换自己的cdn了，作者可以看看什么情况

**Comment by imzbf** [comment]
> cdn的资源全部挂掉了，我换了很多的网都拿不到，已经更换自己的cdn了，作者可以看看什么情况

jsdelivr最近经常挂掉，他们自己的站都有时候挂掉，出现这种情况，最好替换相应的链接。这边在考虑要不要换一个了。

**Comment by ChineseBread** [comment]
> > cdn的资源全部挂掉了，我换了很多的网都拿不到，已经更换自己的cdn了，作者可以看看什么情况
> 
> jsdelivr最近经常挂掉，他们自己的站都有时候挂掉，出现这种情况，最好替换相应的链接。这边在考虑要不要换一个了。

[cdn.js](https://cdnjs.com/)还不错,没有崩过

**Comment by imzbf** [comment]
嗯，计划在2.x版本中备用一到两个站，供奔溃的时候切换，还没开发完，目前就建议自行替换一下

**Comment by imzbf** [comment]
先更新1.6.13版本规避CDN问题
