### ISSUE TITLE
encounting  render delay both in md website and local components

### ISSUE THREAD

**Issue by ChineseBread** [imzbf/md-editor-rt#26]
组件在快速输入内容时右边不会同步render,但是我没有在组件中找到类似startTransition的节流渲染方法啊，官方也有这种情况了
```
onChange={(v: string, completeStatus = true) => {
            if (completeStatus) {
              // 输入中文等语言时，未选择文本不保存历史
              // 撤回将不会出现中间输入内容
              bus.emit(editorId, 'saveHistory', v);
            }
             ->> props.onChange(v);
          }}
```

**Comment by imzbf** [comment]
[`useMarked`](https://github.com/imzbf/md-editor-rt/blob/dev/MdEditor/layouts/Content/hooks.ts#L412), 2.x之后支持配置这个时间，最近作者有点状况，没法很快更新

**Comment by ChineseBread** [comment]
> [`useMarked`](https://github.com/imzbf/md-editor-rt/blob/dev/MdEditor/layouts/Content/hooks.ts#L412), 2.x之后支持配置这个时间，最近作者有点状况，没法很快更新

作者可以在下次更新中试试react18的startTransition，听说不错🤓

**Comment by imzbf** [comment]
嗯，对交互可能会有好处，会考虑的😀

**Comment by imzbf** [comment]
经过测试，编辑器中的组件渲染时间并不需要太长时间。而编译`markdown`文本需要更多的时间，所以没有采用`React18`的特性。这也使得17版本不用做依赖升级。

在`2.x`中，可以通过`MdEditor.config`设置`renderDelay`为`500`或更小来减小输入渲染延迟。
