### ISSUE TITLE
problem about props

### ISSUE THREAD

**Issue by ChineseBread** [imzbf/md-editor-rt#27]
### 2.0版本props中的class在tsx中会报错，要改成className，但是官网给的是class
![image](https://user-images.githubusercontent.com/76460624/170807482-7420339b-fc77-4fdb-8e5b-85d7cf0b8d93.png)

**Comment by imzbf** [comment]
啊这，同步过来的时候没注意，补丁一下先

**Comment by imzbf** [comment]
文档更新了，感谢提醒~
