### ISSUE TITLE
感谢作者，有一个问题说一下

### ISSUE THREAD

**Issue by start-point** [imzbf/md-editor-rt#3]
那个全屏按钮 第一次点击是电脑屏幕全屏 然后 再去点一次 他回不去了 变成了 浏览器(内容)全屏
这是第一次点击
![1](https://user-images.githubusercontent.com/83851349/140693722-b2999fca-899b-42e9-9099-d221275fe8fd.png)
这是第二次
![2](https://user-images.githubusercontent.com/83851349/140846184-b890a631-c1b0-421b-8d50-5d65afdc8fc4.png)

**Comment by imzbf** [comment]
谢谢反馈~

**Comment by imzbf** [comment]
在[1.2.0](https://github.com/imzbf/md-editor-rt/releases/tag/v1.2.0)中该问题已修复辣~
