### ISSUE TITLE
编写正确的 md 文档格式  不高亮

### ISSUE THREAD

**Issue by fuXiangRong** [imzbf/md-editor-rt#30]
```js
interface IUser{
  name: string;
  phone: number; 
  age: number;
}

/*
	假设 李四用户 没有phone和age 属性
	去除单个为 Omit<IUser, 'phone'>
*/
let user2: Omit<IUser, 'phone' | 'age'> = {
  name: '李四'
}
```

作者你好  写这段md格式   预览不会高亮，预览主题和代码主题  设置成什么都没有效果

附上官网 
[图片1](https://webmyapp.oss-cn-beijing.aliyuncs.com/0E05FADB-16BB-44FD-9056-8F7561930D56.png)
[图片2](https://webmyapp.oss-cn-beijing.aliyuncs.com/DA049487-ADCA-483F-A698-60115CBB30B2.png)

**Comment by fuXiangRong** [comment]
高亮   漏打了个 亮字

**Comment by imzbf** [comment]
这个需要优化一下`highlight`，等下个补丁版本更新

**Comment by imzbf** [comment]
在`2.1.1`版本优化了这个问题~
