### ISSUE TITLE
请问图片如何粘贴？

### ISSUE THREAD

**Issue by zdwork** [imzbf/md-editor-rt#31]
请问图片如何粘贴？

**Comment by imzbf** [comment]
就正常复制粘贴就可以呀

**Comment by zdwork** [comment]
请问后发布完成后的内容，前端如何单独渲染呢，或者要参考哪块文档呢

**Comment by zdwork** [comment]
[imzbf.github.io/md-editor-rt](https://imzbf.github.io/md-editor-rt)  这个demo无法粘贴图片

**Comment by zdwork** [comment]
dev-docs 分支

npm install

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: md-editor-rt@2.1.1
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.3 || ^17" from react-redux@7.2.6
npm ERR! node_modules/react-redux
npm ERR!   react-redux@"^7.2.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

npm ERR! A complete log of this run can be found in:

**Comment by zdwork** [comment]
文档属实看不懂 怎么在react里运行呢？

**Comment by imzbf** [comment]
项目都提供了yarn.lock，使用yarn安装依赖就没问题了

**Comment by zdwork** [comment]
![image](https://user-images.githubusercontent.com/24469374/173212739-3baf1443-94e8-49b1-bed8-acfdeeec0af1.png)
空白页呢

**Comment by imzbf** [comment]
请熟悉一下项目哈
