### ISSUE TITLE
编辑时怎么传图片？

### ISSUE THREAD

**Issue by guozi007a** [imzbf/md-editor-rt#34]
在编辑md时，选择`Add Img Link`传图片是有效的，图片可以显示。

但是选择上传图片或者直接CV图片到编辑区，都是无效的，没有反应，图片也不显示。

这是为啥呢？

在https://imzbf.github.io/md-editor-rt 官网上试的。

**Comment by imzbf** [comment]
官网没有做图片上传的服务端，请参考文档的上传图片示例完成上传功能
