### ISSUE TITLE
官网文档错了吧

### ISSUE THREAD

**Issue by Lrunlin** [imzbf/md-editor-rt#38]
![image](https://user-images.githubusercontent.com/54397964/175754004-553a9683-6726-46b3-b4fc-7216fe8f78de.png)
[地址](https://imzbf.github.io/md-editor-rt/demo)

**Comment by imzbf** [comment]
嗯？有什么问题吗

**Comment by Lrunlin** [comment]
npm安装，示例是yarn

**Comment by imzbf** [comment]
这个不是写错了，组件项目全都是用yarn，所以默认了yarn，这里的npm不是特指`npm i`这里的命令
