### ISSUE TITLE
是否可以取消代码高亮，在编辑时不使用他

### ISSUE THREAD

**Issue by Lrunlin** [imzbf/md-editor-rt#39]

**Comment by imzbf** [comment]
这个功能不行，目前也不计划支持，编辑器主打的就是渲染出更适合阅读的markdown文章，如果有需求，可fork后移除highlight功能

**Comment by Lrunlin** [comment]
做成可选项呢，是否启用代码高亮，因为我代码高亮使用的prism，想在查询数据时使用ORM中的get进行高亮

**Comment by Lrunlin** [comment]
我clone一下，自行修改一下吧，谢谢了

**Comment by imzbf** [comment]
> 做成可选项呢，是否启用代码高亮，因为我代码高亮使用的prism，想在查询数据时使用ORM中的get进行高亮

这个建议可以，不过需要点时间来做下个功能版本，目前捉急的话，就先自定义一下吧😄

**Comment by imzbf** [comment]
在尝试开发中无法平衡多编辑器中`marked`配置问题，这个功能不再支持。很抱歉
