### ISSUE TITLE
裁剪图片的拖拽问题和文档内容有标签时图片不展示

### ISSUE THREAD

**Issue by start-point** [imzbf/md-editor-rt#4]
首先第一个问题：裁剪图片的拖拽，当我浏览器上下滚动的时候 鼠标的指针就不再 裁剪图片的窗口上面了
应该是 拖拽的div 到窗口的距离 你这个好像是 到浏览器的距离
其实可以取消拖拽的功能-或者作者去修复一下这个问题
（bug触发：点击裁剪图片 去拖拽他 然后滚动浏览器窗口）

第二个问题：就是文档内容有标签的话 下面在去上传图片就不展示了 （超链接也是如此）
但是如果在标签和图片之间加一个回车 就可以展示了 
![1](https://user-images.githubusercontent.com/83851349/141742730-1281f6d5-22ac-4947-a02c-61af0b3376cc.png)

第三个问题和建议：图片上传功能 默认三个 链接/上传图片/裁剪 可以通过 true/false 去控制他 如果我不想要裁剪功能可以通过配置项给个 裁剪: false; 去掉 
问题：如果markdown组件 放到form表单里面 那个裁剪图片的确定按钮 和form表单的确定按钮会重（点击裁剪图片的确定按钮 form表单就提交了）

*希望作者可以参考一下

**Comment by imzbf** [comment]
谢谢，问题已确认~

关于第三个建议，这边会进一步考虑是否合适~

**Comment by imzbf** [comment]
- 拖拽问题在[1.2.0](https://github.com/imzbf/md-editor-rt/releases/tag/v1.2.0)中得到优化辣~
- 关于标签与文本之前需要换行的问题，目前需要自行处理一下，后续测试marked新版本有优化再行优化
- 关于上传图片菜单控制，目前不做该内容控制
- 关于button对form表单的影响已消除
