### ISSUE TITLE
公司有点怪的需求，图像需要从图像链接执行ajax获取图片真实地址后再渲染图像

### ISSUE THREAD

**Issue by thelastfantasy** [imzbf/md-editor-rt#40]
如题
于是尝试用markedRenderer的renderer.image来实现上述要求
但是实际写代码的时候发现，markedRenderer和renderer.image的返回值类型都写死了（分别返回RewriteRenderer和string）
于是尝试

- renderer.image返回react自定义组件 -> 不是string，失败
- 把renderer.image写成async函数，在函数内部完成ajax请求 -> 返回类型Promise<string>，因为不是要求的string，失败

求解决方法😂

**Comment by imzbf** [comment]
有一个不同步的办法，你重写一下`renderer.image`

```js
renderer.image = (...) => `<img data-src="${src}" >`
```

然后挂载之后获取到文章内容的所有图片标签。分别通过ajax去拿到资源后，再将链接或者文件内容给赋给对应的图片标签。

**Comment by thelastfantasy** [comment]
> 有一个不同步的办法，你重写一下`renderer.image`
> 
> ```js
> renderer.image = (...) => `<img data-src="${src}" >`
> ```
> 
> 然后挂载之后获取到文章内容的所有图片标签。分别通过ajax去拿到资源后，再将链接或者文件内容给赋给对应的图片标签。

这得操作DOM吧...

**Comment by imzbf** [comment]
不可行，环境不同，marked没有虚拟dom的概念
