### ISSUE TITLE
未知bug：图片—添加链接，录入文本信息报错

### ISSUE THREAD

**Issue by coderhn** [imzbf/md-editor-rt#47]
非常感谢大佬提供这么好用的开源markdown编辑器，开源万岁！
![image](https://user-images.githubusercontent.com/47112336/188608974-48708817-fb03-4c11-80ed-0843d19cfe64.png)
我在尝试着将该您编写的库移植到自己的系统中，在执行图片-添加链接的时候报了如下错误：
![image](https://user-images.githubusercontent.com/47112336/188610680-5d500d5c-b591-49b5-be7b-f56893b12501.png)
![image](https://user-images.githubusercontent.com/47112336/188610965-29f3b8f5-b1de-4f2d-b6b2-46a990a14120.png)

这是我的图片上传方法
![image](https://user-images.githubusercontent.com/47112336/188611302-50182db5-8a54-421a-bf55-c1017f7eb91e.png)
这个问题我查了很久，目前不知道是什么原因导致的，能否劳烦您抽个时间看看、给个修复该问题的方向即可！

**Comment by imzbf** [comment]
上传图片的callBack的入参是所有上传的图片链接数组哦

```js
callBack(['https://img.cc/1', 'https://img.cc/1'])
```

可以参考文档这样写[onUploadImg](https://imzbf.github.io/md-editor-rt/docs#%F0%9F%93%B8%20onUploadImg)
