### ISSUE TITLE
@2.2.1暗夜模式下工具栏呈现样式错误

### ISSUE THREAD

**Issue by z2244713679** [imzbf/md-editor-rt#49]
你好。对于 `[md-editor-rt]` 是否用用户交流群呀。
我这边在初始话的时候，给了默认的theme为dark，这个主题连编辑器顶部的工具栏部分都会变成暗黑色，是我哪里写错了吗?

可以在这个链接查看一下详情 [点这里](https://ibb.co/ZKQWBr4)

```js

  import React, { useState } from 'react';
  import MdEditor from 'md-editor-rt';
  import 'md-editor-rt/lib/style.css';
  
  export default (): any => {
    const [text, setText] = useState('hello md-editor-rt！');
    return (
      <>
        <MdEditor theme="dark" modelValue={text} onChange={setText} />
      </>
    );
  };
```

**Comment by z2244713679** [comment]
@imzbf 好的，感谢你的回复。

**Comment by z2244713679** [comment]
@imzbf 我这边看 好像是因为颜色属性是 `fill: currentColor;`  这个属性我理解和继承父级元素-根元素 `color` 的意思，但是我从 `ICON` 往上查找时候 并没有发现 `ICON` 的父级元素-根元素身上有设置 `color` 样式，应该是走了默认的浏览器字体颜色 黑色

**Comment by imzbf** [comment]
只需要给编辑器上层定义一个字体颜色就可以了，最简单的调整：

```css
html {
  color: #999;
}
```

**Comment by z2244713679** [comment]
嗯呢 谢谢🙏

**Comment by imzbf** [comment]
`2.3.0`更新了这个问题~
