### ISSUE TITLE
当标题中包含链接时渲染错误

### ISSUE THREAD

**Issue by Xhofe** [imzbf/md-editor-rt#5]
相关issue：https://github.com/Xhofe/alist/issues/165
我看最新的marked 4.0.4并没有这个问题。

**Comment by imzbf** [comment]
这边尝试一下看

**Comment by Xhofe** [comment]
https://github.com/imzbf/md-editor-rt/blob/242aefad92e48d86b553b9f132fdbf0409e71c2b/MdEditor/Editor.tsx#L451-L455
应该是这个默认实现引号冲突了

**Comment by imzbf** [comment]
已经在`v1.2.2`修复这类问题
