### ISSUE TITLE
编辑器扩展未生效

### ISSUE THREAD

**Issue by z2244713679** [imzbf/md-editor-rt#50]
你好：
这部分是我的代码

  ```js
  
    import React, { FC } from 'react';
    import MdEditor from 'md-editor-rt';
    import 'md-editor-rt/lib/style.css';
    
    const Home: FC = () => (
      <MdEditor
        modelValue=""
        editorId="md-prev"
        defToolbars={[<MdEditor.NormalToolbar title="标记" trigger="测试" onClick={console.log} key="mark-toolbar" />]}
      />
    );
    export default Home;
  
  ```

但是扩展的编辑器并没有生效 trigger 的值为Svg的时候也不行。
还有一个问题是，我应该怎么调节我扩展的功能和原本编辑器默认自带功能的顺序呢？在文档部分没有找到。
或者说有首页那个编辑器的源码吗？
🙏

**Comment by imzbf** [comment]
文档是示列：[https://imzbf.github.io/md-editor-rt/docs#%F0%9F%92%AA%20defToolbars](https://imzbf.github.io/md-editor-rt/docs#%F0%9F%92%AA%20defToolbars)

需要使用`toolbars`api制定内部以及你的扩展的排列顺序

**Comment by z2244713679** [comment]
@imzbf  好的，首先非常感谢你的回复，刚才没有注意到这块的介绍，但是我好像发现了一处错误

```js

 toolbars=['github', '=', 0]

```

是不是应该写为

```js

 toolbars={['github', '=', 0]}

```js

**Comment by imzbf** [comment]
😅手搓的文档，没注意写错了，确实应该这样
