### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by z2244713679** [imzbf/md-editor-rt#51]
hello 提一个小建议哈
我使用了一下 `<ModalToolbar />`这个弹窗组件，有一点的体验不是很好，发现弹窗部分的位置不是那种绝对的居中，只有首屏的时候是居中状态，这个改成自适应的居中是不是会更好一点，当然，我这边也可以添加样式去更改，这是感觉默认就是自适应居中会更好一点😁

**Comment by imzbf** [comment]
目前看起来是居中的呀

**Comment by z2244713679** [comment]
第一次展现是居中的 如果屏幕缩放之后 就是不是居中的了
[如图](https://i.postimg.cc/Cxbm74vb/Snipaste-2022-10-01-19-48-08.png)

**Comment by imzbf** [comment]
这个表现是正常的哈。因为才用的弹窗是可拖动的，如果已经拖动过了，页面宽度变化后自动居中的话，会有操作冲突。现在的理念是保持使用时操作一致。
