### ISSUE TITLE
代码显示部分有一个白框如何消除？

### ISSUE THREAD

**Issue by 1219521375** [imzbf/md-editor-rt#53]
![image](https://user-images.githubusercontent.com/32407091/200989806-fbd22934-f66d-4028-9c11-31f6fe01feaf.png)

```js
<MdEditor modelValue={blog_content} editorId={editorId}  />
```
如上图，markdown预览部分代码块会有个白色外框包裹，如何才能将其消除？

**Comment by imzbf** [comment]
应该是你的项目中的样式冲突了，这个自行调试一下样式就可以了
