### ISSUE TITLE
如何取消preview-only时的滚动条？

### ISSUE THREAD

**Issue by 1219521375** [imzbf/md-editor-rt#55]
当只显示preview部分且markdown内容较长时，整个组件内会有滚动条，如何让这个这个滚动条消失，即整个页面长度随preview内markdown内容长度的变化而变化，用浏览器滚动条滚动来显示整个markdown内容
```html
<MdEditor  modelValue={blog_content} editorId={editorId} previewOnly={true} />
```

![image](https://user-images.githubusercontent.com/32407091/201642655-53c362b1-e8a7-4140-a51a-cc39c65a2df6.png)

**Comment by 1219521375** [comment]
目前似乎markdown组件的高度是随屏幕高度变化而变化的，请问有什么办法能让高度固定或者手动设置吗

**Comment by imzbf** [comment]
这个组件并没有设置限制高度，你这是因为组件外部元素被你限制了才出现的情况

**Comment by 1219521375** [comment]
> 这个组件并没有设置限制高度，你这是因为组件外部元素被你限制了才出现的情况

感谢，发现是其他地方用.md-editor设置了css造成了影响。
