### ISSUE TITLE
输入后追加样式优化

### ISSUE THREAD

**Issue by KevinYou9** [imzbf/md-editor-rt#56]
希望可以在已输入文字在点击后样式后直接将文字格式化, 而非追加样式在后面
![image](https://user-images.githubusercontent.com/115126247/203938702-865315de-4f4a-4916-b6a1-d24fc5519fd9.png)

**Comment by imzbf** [comment]
你是指类似添加标题的时候自动换行吗？

**Comment by KevinYouu** [comment]
原本的效果

https://user-images.githubusercontent.com/46970005/203994834-5b74aa98-64e3-43e9-aea5-bc2c6993fc9c.mov

期望的效果

https://user-images.githubusercontent.com/46970005/203994336-549734cc-a563-452e-afec-d8dfdd3a0f52.mov

**Comment by imzbf** [comment]
感谢您的演示，之前有讨论过这种形式，以及所见所得的形式。编辑器的实现原理做不到，几乎需要重启一个项目再开发，所以很抱歉，目前没有足够的人力去做这个调整。
