### ISSUE TITLE
大佬，快捷键不能触发

### ISSUE THREAD

**Issue by ethanlamm** [imzbf/md-editor-rt#58]
stack: electron + react
按ctrl + s 不能触发 onSave 回调函数(已确保焦点在编辑器区域)，其他的ctrl+ 1~6、ctrl + B、ctrl + O 等也不能触发
是要打开某项配置，才能出发这些快捷键的吗？望大佬答复

**Comment by ethanlamm** [comment]
查看 issues https://github.com/imzbf/md-editor-rt/issues/52 , 在vite-react中使用，还是出现同样的情况

https://user-images.githubusercontent.com/101323067/208035014-d6391574-4ec0-4460-9313-c79f4ed197b2.mp4

**Comment by ethanlamm** [comment]
查看issues https://github.com/imzbf/md-editor-rt/issues/52 ，在vite-react中使用，还是出现该issues描述的情况

![Vite-React](https://user-images.githubusercontent.com/101323067/208035829-b845d974-2ef2-43dd-80bf-91c09a19f7e7.gif)

不是很理解快捷键触发的时机

**Comment by imzbf** [comment]
在输入框中按快捷键`ctrl + s`才能正确触发，因为逻辑判断了触发的元素是不是编辑器中的这个输入框。这样才不能影响到你页面中其他的功能。比如：你的页面定义了`ctrl + s`是快速保存你的文章，而编辑器全局给你拦截了，你会感觉到很苦恼，所以只处理输入框获取到焦点的情况。

electron是因为这个原因吗？不是的话，这边找时间尝试一下

**Comment by ethanlamm** [comment]
大佬，看到你提交修改代码[fix: shortcut key cannot be triggered correctly](https://github.com/imzbf/md-editor-rt/commit/ccafa44b7624f886b1fb6ba6b223ec88f7cb96d9)后，再次在普通web和elcetron使用，还是存在electron不能触发和web页面触发另存为行为而没有触发onSave回调。

学习阅读了一下你提交的代码，发现你使用`event.preventDefault()`来阻止事件间冒泡(如果是这样的话)，`event.preventDefault()`并不能阻止合成事件之间的冒泡(在react中)，使用`e.stopPropagation()`或者`e.nativeEvent.stopImmediatePropagation()`或许更有效果

如果说错了，请指正😊

**Comment by imzbf** [comment]
修改了还没发布，我本地构建出测试版在`elcetron`里通过了。源码中还存在一些问题，还有修复一下，估计要周末才能更新。

关于`preventDefault`，只是阻止了默认的行为，比如，`ctrl+s`时，不会弹出保存页面的窗口了。由于这是js原始的方式监听的事件，所以不用去考虑`react`相关的问题哈。一般情况不用去阻止事件冒泡

**Comment by ethanlamm** [comment]
> 修改了还没发布，我本地构建出测试版在`elcetron`里通过了。源码中还存在一些问题，还有修复一下，估计要周末才能更新。
> 
> 关于`preventDefault`，只是阻止了默认的行为，比如，`ctrl+s`时，不会弹出保存页面的窗口了。由于这是js原始的方式监听的事件，所以不用去考虑`react`相关的问题哈。一般情况不用去阻止事件冒泡

好的，谢谢你的解答😘

**Comment by imzbf** [comment]
`2.7.0`已修复了相关问题~
