### ISSUE TITLE
输入是 按下两次tab 就会变成一个 代码输入框

### ISSUE THREAD

**Issue by z2244713679** [imzbf/md-editor-rt#59]
1.输入是 按下两次tab 就会变成一个 代码输入框
2.一个小点：[link](https://imzbf.github.io/md-editor-v3/demo#%F0%9F%A7%99%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%B0%83%E6%95%B4%E7%BC%96%E8%BE%91%E5%99%A8%E6%A0%B7%E5%BC%8F)
- ` --md-scrollbar-thumb-avtive-color`单词`avtive`好像错了

**Comment by imzbf** [comment]
1. 描述1中的，好像所有编译库默认这样的，我也是才知道这个规则，这边决定是保持现状。
2. 感谢提醒文档错误

**Comment by z2244713679** [comment]
好的 了解

**Comment by z2244713679** [comment]
还有一个问题是 如果关闭掉预览之后 滚动内容 再打开预览的时候 滚动条不会自动同步

**Comment by imzbf** [comment]
> 还有一个问题是 如果关闭掉预览之后 滚动内容 再打开预览的时候 滚动条不会自动同步

这个问题在`2.8.1`修复了，你试试

**Comment by z2244713679** [comment]
> > 还有一个问题是 如果关闭掉预览之后 滚动内容 再打开预览的时候 滚动条不会自动同步
> 
> 这个问题在`2.8.1`修复了，你试试

我在`2.8.1`版本发现还是有这个问题 现在看官网的文档教程中的示例还存在这个问题 但是不确定版本

**Comment by imzbf** [comment]
> 还有一个问题是 如果关闭掉预览之后 滚动内容 再打开预览的时候 滚动条不会自动同步

这个问题是不会立刻同步还是滚动的时候都不再同步了？

**Comment by z2244713679** [comment]
@imzbf ？再次打开不会立刻同步

**Comment by imzbf** [comment]
> @imzbf ？再次打开不会立刻同步

是的，目前没有优化这个问题。计划作为优化项在后面版本调整

**Comment by z2244713679** [comment]
好的 了解 @imzbf  辛苦啦 谢谢

**Comment by imzbf** [comment]
在2.9.0优化了相关功能~
