### ISSUE TITLE
在react路由跳转的时候会报错

### ISSUE THREAD

**Issue by PrinceH** [imzbf/md-editor-rt#6]
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

![1638326765(1)](https://user-images.githubusercontent.com/33449867/144162666-58f9fd64-d384-4c28-aea7-aed35efd0f24.png)
![1638326801(1)](https://user-images.githubusercontent.com/33449867/144162721-5fc71a5a-937d-4283-bb0d-1a4bf3d4ae3d.png)

**Comment by imzbf** [comment]
nextjs环境吗

**Comment by imzbf** [comment]
能否提供一个可还原问题的仓库？

**Comment by PrinceH** [comment]
用的是react ant pro 我复现一下给你

**Comment by imzbf** [comment]
> 用的是react ant pro 我复现一下给你

好的

**Comment by imzbf** [comment]
> 用的是react ant pro 我复现一下给你

这边在ant pro@5.0.0上没有复现这个问题，请问你这边的版本是？

**Comment by PrinceH** [comment]
git@github.com:PrinceH/react.git 你看看多个Editor才会出现这样子的问题

**Comment by ChenGuanglin0924** [comment]
我同样也遇到这个问题  请问一下解决了吗 @imzbf

**Comment by imzbf** [comment]
已经找到解决办法了，请等下一个补丁版本哈 @ChenGuanglin0924

**Comment by imzbf** [comment]
在`v1.2.3`中已修复该问题~
