### ISSUE TITLE
MathJax in title bug

### ISSUE THREAD

**Issue by Error-Yuan** [imzbf/md-editor-rt#61]
When using mathjax in title, for example, ```# $1+1=2$```, there will be some bug, it is rendered like this:

> # $1+1=2$ >" $1+1=2$ >" $1+1=2$

**Comment by Error-Yuan** [comment]
How to fix it?

**Comment by imzbf** [comment]
This seems to be a bug. I will fix it in the next version.

**Comment by imzbf** [comment]
Because the title is used as the ID of itself, the mathematical formula is appended multiple times

**Comment by Error-Yuan** [comment]
Thanks!
