### ISSUE TITLE
Is there a way to change text color?

### ISSUE THREAD

**Issue by serzhan181** [imzbf/md-editor-rt#63]
The title says for itself. I want to be able to change the text color, the following just doesn't work (className property does not either)
```jsx
<Editor
   style={{
     color: "white",
   }}
/>
```

**Comment by imzbf** [comment]
The text in `textarea` or in preview  element？

**Comment by serzhan181** [comment]
I believe in preview element. But i think its better to show the picture

![изображение](https://user-images.githubusercontent.com/67381256/227726204-5c48f632-346d-4cf3-8b03-e3b5b38b44a6.png)

So the title is seperate, the body is rendered through Editor component with previewOnly property. As you see colors dont match

**Comment by imzbf** [comment]
```css
.md-editor-dark .md-editor-preview {
  --md-theme-color: red;
}
```

all vars at [change-styles](https://github.com/imzbf/md-editor-rt#%EF%B8%8F-change-styles)

**Comment by serzhan181** [comment]
Thanks! it helps
