### ISSUE TITLE
gif images are not supported

### ISSUE THREAD

**Issue by dzmitry-duboyski** [imzbf/md-editor-rt#64]
Tell me, are you planning to add support for gif images?
Now when I try to add a gif image, I get an error in the console.

Error message from console:
```stacktace
index.d5c13118.js:146 Uncaught (in promise) Q {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
```

Screenshot:
![image](https://user-images.githubusercontent.com/38065632/228781040-2c9546db-471b-484e-9d6f-6cdc49793afa.png)

**Comment by imzbf** [comment]
Check your api for uploading images.

**Comment by dzmitry-duboyski** [comment]
@imzbf  Ok thanks, I'll check the api and let you know

**Comment by dzmitry-duboyski** [comment]
@imzbf  Thanks, the problem was really not related to **md-editor-rt**
