### ISSUE TITLE
error while inserting large image

### ISSUE THREAD

**Issue by dzmitry-duboyski** [imzbf/md-editor-rt#65]
Cannot insert [large image](https://user-images.githubusercontent.com/38065632/228785417-a5784533-35c8-4a5d-a6b0-0f981d653624.jpg). When I try to paste a  [large image](https://user-images.githubusercontent.com/38065632/228785417-a5784533-35c8-4a5d-a6b0-0f981d653624.jpg), I get an error in the console.

Screenshot:
![image](https://user-images.githubusercontent.com/38065632/228785287-2826003f-0071-4346-af18-19f4f9a30551.png)

**Comment by imzbf** [comment]
If you are uploading it, check your api for uploading

**Comment by dzmitry-duboyski** [comment]
@imzbf On the demo page, I also get an error when  try attaching a large image.

Video: https://drive.google.com/file/d/1uRql6eMELeQ1QRa4ZgMaMb8pt-vyStRX/view?usp=share_link

**Comment by dzmitry-duboyski** [comment]
@imzbf Ok thanks, I'll check the api and let you know

**Comment by imzbf** [comment]
I haven't prepared a service for the document, so we can't upload images here😀

**Comment by dzmitry-duboyski** [comment]
Thanks, the problem was really not related to **md-editor-rt**
