### ISSUE TITLE
使用npm下载后运行项目报错

### ISSUE THREAD

**Issue by 25284921941** [imzbf/md-editor-rt#69]
ERROR in ./node_modules/md-editor-rt/lib/md-editor-rt.mjs 1602:13-14
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
 @ ./src/pages/Document/add/index.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

**Comment by imzbf** [comment]
方便给一份还原问题的代码不，基础环境就可以

**Comment by 25284921941** [comment]
换成webpack5后这个报错没有了
