### ISSUE TITLE
【建议】部分建议

### ISSUE THREAD

**Issue by ChenGuanglin0924** [imzbf/md-editor-rt#7]
1. 在插入表格等块状元素时建议换行
![image](https://user-images.githubusercontent.com/22443356/144225724-cd47e927-2ccf-4d72-ab2d-6142a16a5480.png)
2. 添加表格时建议支持用户选择行列
![image](https://user-images.githubusercontent.com/22443356/144225890-f360a8ac-5216-4196-9c76-f9035c4f9726.png)

**Comment by imzbf** [comment]
关于第一点有考虑换行，但是情况过于复杂，所以交给使用者在插入时自行处理。第二点内容会考虑在下个功能版本加入，感谢建议。

**Comment by ChenGuanglin0924** [comment]
textarea 支持 placeholder

**Comment by whereabouts** [comment]
previewOnly 预览模式下时为什么不支持响应式呢，存在性能问题吗？是否支持响应式这个可以做成可配置可选择的呢

**Comment by whereabouts** [comment]
快捷键的可以做成可配置的吗，默认开启，选择性关闭，可能并不是所有用户都需要快捷键，因为像我的话，还是更习惯操作系统的快捷键，而且windows和mac有部分差异

**Comment by imzbf** [comment]
> previewOnly 预览模式下时为什么不支持响应式呢，存在性能问题吗？是否支持响应式这个可以做成可配置可选择的呢

是更新了`modelValue`的数据页面没有变化么？

**Comment by imzbf** [comment]
> 快捷键的可以做成可配置的吗，默认开启，选择性关闭，可能并不是所有用户都需要快捷键，因为像我的话，还是更习惯操作系统的快捷键，而且windows和mac有部分差异

这个问题之前有提到过，因为涉及到编辑器内置的文本替换规则，会导致系统一部分快捷键无法在编辑器中使用（例如：插入表格是在所有文本中间插入了表格文本，然后直接替换整个文本，这样的操作相对于系统的的撤回、取消撤回就不可用了）

**Comment by whereabouts** [comment]
> > previewOnly 预览模式下时为什么不支持响应式呢，存在性能问题吗？是否支持响应式这个可以做成可配置可选择的呢
> 
> 是更新了`modelValue`的数据页面没有变化么？

不是，是开发者工具拖动改变窗口宽度时没有随着宽度缩小，放大倒是没问题的

**Comment by imzbf** [comment]
> 不是，是开发者工具拖动改变窗口宽度时没有随着宽度缩小，放大倒是没问题的

预览内容区域时根据外部宽度来的，你看看是不是你上层写死了宽度

**Comment by whereabouts** [comment]
> > 不是，是开发者工具拖动改变窗口宽度时没有随着宽度缩小，放大倒是没问题的
> 
> 预览内容区域时根据外部宽度来的，你看看是不是你上层的样式影响了你在小屏下的表现。我的博客上面表现没有什么问题。
> 
> [imbf.cc](https://imbf.cc)

确实是有其他元素把屏幕撑开了，感谢

**Comment by whereabouts** [comment]
> > 快捷键的可以做成可配置的吗，默认开启，选择性关闭，可能并不是所有用户都需要快捷键，因为像我的话，还是更习惯操作系统的快捷键，而且windows和mac有部分差异
> 
> 这个问题之前有提到过，因为涉及到编辑器内置的文本替换规则，会导致系统一部分快捷键无法在编辑器中使用（例如：插入表格是在所有文本中间插入了表格文本，然后直接替换整个文本，这样的操作相对于系统的的撤回、取消撤回就不可用了）

我测试了一下确实存在这个问题，那可能目前的问题是没有对mac做适配，希望再加一个取消撤回的快捷键 Ctrl + Y，建议大佬可以参考下csdn等一些已经比较成熟的，撤回规则上我试了下感觉csdn的更友好一点，不会一整大片的被撤回，这可能导致很多不想撤回的内容被撤回了，实际上很多时候需要撤回的内容只是短时间内新输入的较短内容

**Comment by whereabouts** [comment]
![image](https://user-images.githubusercontent.com/36706912/145929035-d48475b8-b26d-4822-bf74-92b894ce00bc.png)

**Comment by imzbf** [comment]
> ![image](https://user-images.githubusercontent.com/36706912/145929035-d48475b8-b26d-4822-bf74-92b894ce00bc.png)

你这个问题怎么复现😳

**Comment by whereabouts** [comment]
> > ![image](https://user-images.githubusercontent.com/36706912/145929035-d48475b8-b26d-4822-bf74-92b894ce00bc.png)
> 
> 你这个问题怎么复现😳

从一个其他页面刚跳转到编辑页面后，随便输入字符，快捷键撤回，能撤回成功，但是有这个报错。另外撤回后鼠标光标位置有点乱跳

**Comment by imzbf** [comment]
> 

好的，谢谢。

**Comment by imzbf** [comment]
这块内容的建议和问题在[v1.3.0](https://github.com/imzbf/md-editor-rt/releases/tag/v1.3.0)修复添加。感谢跟进~
