### ISSUE TITLE
仅预览模式没有提供目录的功能吗

### ISSUE THREAD

**Issue by imyuanli** [imzbf/md-editor-rt#70]
目前就是在仅预览模式显示博客，但是缺少目录，能自动生成吗，不行的话只能自己通过 onGetCatalog实现

**Comment by imzbf** [comment]
有呀，参考一下`dev-docs`的使用源码

https://github.com/imzbf/md-editor-rt/blob/docs/src/layouts/Catalog/index.tsx

**Comment by imyuanli** [comment]
@imzbf  已经解决了！ 感谢
