### ISSUE TITLE
打包提示： Cannot find module 'marked' or its corresponding type declarations.

### ISSUE THREAD

**Issue by xiaoxing92** [imzbf/md-editor-rt#71]
node_modules/md-editor-rt/lib/MdEditor/type.d.ts:2:48 - error TS2307: Cannot find module 'marked' or its corresponding type declarations.
2 import type { marked, Renderer, Slugger } from 'marked';
                                                 ~~~~~~~~
node_modules/md-editor-rt/lib/MdEditor/type.d.ts:372:22 - error TS2707: Generic type 'FocusEvent<T>' requires between 0 and 1 type arguments.
372     onBlur?: (event: FocusEvent<HTMLTextAreaElement, Element>) => void;
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/md-editor-rt/lib/MdEditor/type.d.ts:376:23 - error TS2707: Generic type 'FocusEvent<T>' requires between 0 and 1 type arguments.
376     onFocus?: (event: FocusEvent<HTMLTextAreaElement, Element>) => void;

**Comment by imzbf** [comment]
用什么打的包，编辑器版本是什么
