### ISSUE TITLE
选中文本框开始输入内容时 不显示光标 不知道选中没选中  输入值后才有

### ISSUE THREAD

**Issue by Sole-BadGuy** [imzbf/md-editor-rt#73]
![image](https://github.com/imzbf/md-editor-rt/assets/76092631/4aeb4021-c30b-4fd2-ab4a-bf3b29b351e0)
输入值后
![image](https://github.com/imzbf/md-editor-rt/assets/76092631/1efd885b-59b1-4fbd-b10b-e7b9c1d3d0d8)

**Comment by imzbf** [comment]
在4.0.0版本优化了这个问题，注意使用方式
