### ISSUE TITLE
默认主题的h1和h2的字体大小一样大

### ISSUE THREAD

**Issue by Sole-BadGuy** [imzbf/md-editor-rt#74]
![image](https://github.com/imzbf/md-editor-rt/assets/76092631/e6a46f60-d736-4952-98e8-d84c1b633032)

**Comment by imzbf** [comment]
抱歉，验证的主题不一样，回顾了一下代码，默认主题的一级标题的字体大小确实被覆盖得和二级一样。对你影响很大的话，建议暂时在您的项目里补充对`h1`标签的样式设置。

这个问题会在下个补丁版本修复

**Comment by imzbf** [comment]
4.0.1优化了该问题~

**Comment by Sole-BadGuy** [comment]
> 4.0.1优化了该问题~

感谢开源维护
