### ISSUE TITLE
大佬可以支持自定义渲染器吗

### ISSUE THREAD

**Issue by gsgs-libin** [imzbf/md-editor-rt#75]
类似这个https://codesandbox.io/s/react-mde-latest-forked-f9ti5?file=/src/index.js

他使用了react-markdown渲染

**Comment by imzbf** [comment]
有配置的[入口](https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%92%B4%20%E9%85%8D%E7%BD%AE%E7%BC%96%E8%BE%91%E5%99%A8)

**Comment by gsgs-libin** [comment]
谢谢大佬，用自带的就非常棒了

**Comment by gsgs-libin** [comment]
@imzbf 大佬，还有一个问题，我想请教下，如果想跟这个文档一样https://imzbf.github.io/md-editor-rt/zh-CN/docs，左边是内容，右边是目录，是不是看这个git的源码就行了？

**Comment by imzbf** [comment]
> @imzbf 大佬，还有一个问题，我想请教下，如果想跟这个文档一样[跳转](https://imzbf.github.io/md-editor-rt/zh-CN/docs)，左边是内容，右边是目录，是不是看这个git的源码就行了？

是的，源码在`dev-docs`分支

**Comment by gsgs-libin** [comment]
> > @imzbf 大佬，还有一个问题，我想请教下，如果想跟这个文档一样[跳转](https://imzbf.github.io/md-editor-rt/zh-CN/docs)，左边是内容，右边是目录，是不是看这个git的源码就行了？
> 
> 是的，源码在`dev-docs`分支

好嘞，收

**Comment by Fuzhang1** [comment]
您好，大佬，我想问一下自定义右侧markdown渲染器的入口在哪里，看文档没有找到。公司需求要支持类似mdx的格式，想自定义一下右侧的渲染。谢谢大佬

**Comment by imzbf** [comment]
> 您好，大佬，我想问一下自定义右侧markdown渲染器的入口在哪里，看文档没有找到。公司需求要支持类似mdx的格式，想自定义一下右侧的渲染。谢谢大佬

在这里
https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%8D%A4%20markdownItConfig

`markdownItConfig`和`markdownItPlugins`，具体的规则需要参考`markdown-it`

**Comment by Fuzhang1** [comment]
欧，就是相当于我们只能在markdown-it的基础上做自定义的扩展，没有办法说完全自定义右侧的渲染了是吗

**Comment by imzbf** [comment]
> 欧，就是相当于我们只能在markdown-it的基础上做自定义的扩展，没有办法说完全自定义右侧的渲染了是吗

是的

**Comment by Fuzhang1** [comment]
谢谢大佬
