### ISSUE TITLE
Two editors textarea get render.

### ISSUE THREAD

**Issue by ammar20175** [imzbf/md-editor-rt#78]
two editors textarea get renders.problem when we use the toolbar.the toolbars options are applied to the 2 editor textarea which is hidden it create problem.
and the scrollAuto={false} also dont work.

![issue](https://github.com/imzbf/md-editor-rt/assets/125857714/7e2f6161-d189-4563-b664-d347422af3e5)

here is my code 

![code](https://github.com/imzbf/md-editor-rt/assets/125857714/4a01da8c-531c-47a0-b3de-db473cbb17d1)

**Comment by imzbf** [comment]
Set different `editorId`

**Comment by ammar20175** [comment]
The editorId is not helping to solve the issue.
and the preview button in the toolbar is behaving the opposite.on click it show the markdown not the content.

**Comment by imzbf** [comment]
I'm sorry. This seems to be a bug.

**Comment by imzbf** [comment]
I found this component cannot work when using `<React.StrictMode>`, I'll try upgrading. 

And to make it work correctly, try removing `<React.StrictMode>` currently.

**Comment by imzbf** [comment]
https://github.com/facebook/react/issues/24502

**Comment by ammar20175** [comment]
currently it work properly when the strickmode is remove.But will be more helpful if its upgraded.
Btw its an amazing editor.

**Comment by imzbf** [comment]
I optimized it in version 4.0.2

**Comment by ammar20175** [comment]
Thanks Alot.
