### ISSUE TITLE
更新1.3.0 出现的问题

### ISSUE THREAD

**Issue by start-point** [imzbf/md-editor-rt#8]
Failed to compile
./node_modules/_md-editor-rt@1.3.0@md-editor-rt/lib/md-editor-rt.es.js
Module build failed (from ./node_modules/_@umijs_deps@3.5.20@@umijs/deps/compiled/babel-loader/index.js):
TypeError: /home/admin/cyl01143493/cybersec/bkcsportal/node_modules/_md-editor-rt@1.3.0@md-editor-rt/lib/md-editor-rt.es.js: symbol.charCodeAt is not a function

项目现在都部署不了 我这边暂时没看出 是什么问题

来问一下作者 是不是包的问题

本来以为是更新1.3.0 出现的 然后 我安装1.2.1了  还是有这个问题

**Comment by imzbf** [comment]
尝试一下删除node_modules重新安装相关依赖呢。

**Comment by start-point** [comment]
node_modules 删除掉了  md-editor-rt 依赖也删除掉了  重新安装 md-editor-rt 就出现 上述问题还是没解决  如果你这边 没问题的话 我这边再看看 在排查一下 是不是别的依赖或者是什么导致的

**Comment by imzbf** [comment]
> node_modules 删除掉了 md-editor-rt 依赖也删除掉了 重新安装 md-editor-rt 就出现 上述问题还是没解决 如果你这边 没问题的话 我这边再看看 在排查一下 是不是别的依赖或者是什么导致的

确实没有发现有类似的问题，因为它已经在github-page上的发布成功了，不然文档页面就无法查看。如果方便的话可以给下项目，大家可以看看有没有类似的问题。

**Comment by start-point** [comment]
项目 可能给不了 因为是公司内网项目  那个问题 他不会影响线上用  只是在开发环境中 出现上述错误  怎么说呢  就是可以用 但是报那个错误不能部署

**Comment by start-point** [comment]
下班 我自己弄一下看看 要是有问题 再跟你说 没问题 可能是公司项目 别的包或者是什么弄得 因为他们 也弄了一些东西

代码 是这样 一直没动过

import { request } from '@alipay/bigfish';
import { useState } from 'react';
import Editor from 'md-editor-rt';
import 'md-editor-rt/lib/style.css';

export const Md = ({ onRichData, passRichData }) => {
//passRichData  默认markdown文本数据 
  const [text, setText] = useState(passRichData);

  const toolbars = [
    'bold',
    'underline',
    'italic',
    '-',
    'strikeThrough',
    'title',
    'sub',
    'sup',
    'quote',
    'unorderedList',
    'orderedList',
    '-',
    'codeRow',
    'code',
    'link',
    'image',
    'table',
    'mermaid',
    '-',
    'revoke',
    'next',
    // 'save',
    '=',
    'pageFullscreen',
    // 'fullscreen',
    'preview',
    'htmlPreview',
    'catalog',
  ];
  const onUploadImg = async (files, callback) => {
    const res = await Promise.all(
      Array.from(files).map((file) => {
        return new Promise((rev, rej) => {
          const formData = new FormData();
          formData.append('file', file);
          request('/api/file/upload', {
            method: 'POST',
            body: formData,
            skipErrorHandler: true, // 防止报错 自己去鉴权 不用bigfish内置的
          })
            .then((ress) => {
              rev(ress);
            })
            .catch((errorMsg) => {
              rej(errorMsg);
            });
        });
      }),
    );

    callback(res.map((item) => item.data.url));
  };

  return (
    <Editor
      toolbars={toolbars}
      modelValue={text || ''}
      onUploadImg={onUploadImg}
      onChange={(modelValue) => {
        onRichData(modelValue);
        setText(modelValue);
      }}
    />
  );
};

**Comment by start-point** [comment]
新建的项目 用了之后 没有那个问题 可能就是公司项目本身 别的问题了  那这个issues 就先这样吧

**Comment by kiinlam** [comment]
这问题不能关啊，我也遇到了，目前是v1.4.2。
![image](https://user-images.githubusercontent.com/5861519/150715553-ea40c571-4576-472b-a5e2-64e68d0a9791.png)

同样是 umi 框架。

**Comment by imzbf** [comment]
> 这问题不能关啊，我也遇到了，目前是v1.4.2。 ![image](https://user-images.githubusercontent.com/5861519/150715553-ea40c571-4576-472b-a5e2-64e68d0a9791.png)
> 
> 同样是 umi 框架。

根据上面的伙伴描述，这个问题多出自于本身项目依赖。

刚才这边也是用了`"umi": "^3.5.0"`做了尝试，没有出现该问题。建议那边也尝试一下移除node_modules重新安装或重新创建`umi`项目。如果仍然出现类似问题，可以的话提供一下源码，这边协助查找问题。

**Comment by start-point** [comment]
> 这问题不能关啊，我也遇到了，目前是v1.4.2。 ![image](https://user-images.githubusercontent.com/5861519/150715553-ea40c571-4576-472b-a5e2-64e68d0a9791.png)
> 
> 同样是 umi 框架。


这个问题 我这边跟你一样 没有解决 暂时搁置的 用了自己公司开发的一个组件        这个问题 找不到原因 你新建一个项目引入这个组件又没有问题

**Comment by xiaoniuge** [comment]
TypeError: /Users/root1/study/battle/reactjs/react-library/node_modules/md-editor-rt/lib/md-editor-rt.es.js: symbol.charCodeAt is not a function

**Comment by imzbf** [comment]
> TypeError: /Users/root1/study/battle/reactjs/react-library/node_modules/md-editor-rt/lib/md-editor-rt.es.js: symbol.charCodeAt is not a function

最新版的问题吗？方便给下完整的错误信息不。还有这边的设备环境信息。
