### ISSUE TITLE
插入表情后，会直接选中，再选新表情，会替换刚才选择的表情，建议光标放到插入的表情后面

### ISSUE THREAD

**Issue by dxhuii** [imzbf/md-editor-rt#80]
<img width="880" alt="image" src="https://github.com/imzbf/md-editor-rt/assets/2328917/feae9ffc-c511-4b54-81b2-d10b1dc5ac12">

**Comment by imzbf** [comment]
你可以自己调整要不要选择，以及插入后光标的位置

https://imzbf.github.io/md-editor-rt/zh-CN/docs#%F0%9F%92%89%20insert

参入方法有几个入参，你参考一下

**Comment by dxhuii** [comment]
好的。谢谢

> 你可以自己调整要不要选择，以及插入后光标的位置
> 
> https://imzbf.github.io/md-editor-rt/zh-CN/docs#%F0%9F%92%89%20insert
> 
> 参入方法有几个入参，你参考一下
