### ISSUE TITLE
严格模式下，滚动的时候控制台报错

### ISSUE THREAD

**Issue by LiShuxue** [imzbf/md-editor-rt#81]
在 React18.x 的严格模式下`<React.StrictMode>`，滚动时候控制台报错：
React项目是用的vite模板，本地开发的时候。

<img width="802" alt="截屏2023-06-01 15 22 13" src="https://github.com/imzbf/md-editor-rt/assets/20234214/60345866-5adb-4456-9045-efed2ef7ebc2">

**Comment by imzbf** [comment]
文档主页好像就是这样做的，但是还原不了这个问题，是有其他的什么操作才能还原吗？

方便的话提供一份能还原问题的最小环境，帮助定位问题。

**Comment by LiShuxue** [comment]
我今天上午创建了个demo项目去复现了该问题，并且录制了复现的视频。

复现步骤：
1. 克隆该项目：`git clone https://github.com/LiShuxue/demo.git`
2. 进入项目目录：`cd demo`
3. 安装依赖：`pnpm i`
4. 运行：`pnpm dev`
5. 打开浏览器：localhost:8002
6. 在markdown区域连续输入1，每输入一个1按两下enter进行隔行输入，直到超过markdown输入区域。快速操作，即可复现。

**Comment by imzbf** [comment]
> 我今天上午创建了个demo项目去复现了该问题，并且录制了复现的视频（视频有点大，我看看怎么发给你，要不加个微信？我的15822472510）。
> 
> 复现步骤：
> 
> 1. 克隆该项目：`git clone https://github.com/LiShuxue/demo.git`
> 2. 进入项目目录：`cd demo`
> 3. 安装依赖：`pnpm i`
> 4. 运行：`pnpm dev`
> 5. 打开浏览器：localhost:8002
> 6. 在markdown区域连续输入1，每输入一个1按两下enter进行隔行输入，直到超过markdown输入区域。快速操作，即可复现。

收到，我在项目里试试，不行再看看你的视频

**Comment by imzbf** [comment]
我在`4.0.4`中修复了这个问题，试试看

**Comment by LiShuxue** [comment]
可以了
