### ISSUE TITLE
是否可以支持自定义previewTheme

### ISSUE THREAD

**Issue by faye1225** [imzbf/md-editor-rt#84]
如题，可以定制 标题间距、链接样式等

**Comment by imzbf** [comment]
可以呀，自定义一套主题，编辑器的主题代码在[markdown-theme](https://github.com/imzbf/markdown-theme)这个仓库的

如果是完整的，也欢迎提交PR到[md-editor-extension](https://github.com/imzbf/md-editor-extension)，这是编辑器的共享扩展仓库

**Comment by faye1225** [comment]
请问如何只修改部分样式呢～比如我只想修改link hover 🥹

**Comment by imzbf** [comment]
> 请问如何只修改部分样式呢～比如我只想修改link hover 🥹

每个主题的这些的定义不一样，所以只能通过更高优先级的选择器来覆盖原样式，像这是[github主题](https://github.com/imzbf/markdown-theme/blob/develop/src/themes/github/modules/link.scss)的定义，而[默认主题](https://github.com/imzbf/markdown-theme/blob/develop/src/themes/default/modules/link.scss)是这样的。
