### ISSUE TITLE
Nested List with proper icon

### ISSUE THREAD

**Issue by Udayendu** [imzbf/md-editor-rt#88]
### Feature Request:
Currently its supporting nested list but icons are not different based on the list level. It would be nice to have proper list icon before the list name as available in the below image.

## Current List View
![image](https://github.com/imzbf/md-editor-rt/assets/1809177/78f38203-90d7-4860-af68-c2e236bec4ae)

## Future List View
![image](https://github.com/imzbf/md-editor-rt/assets/1809177/f908cd7b-acfd-4df6-ae94-8a6f1210238f)

**Comment by imzbf** [comment]
Fixed in `4.2.2`.
