### ISSUE TITLE
左边编辑区域可以高亮吗

### ISSUE THREAD

**Issue by lin-mt** [imzbf/md-editor-rt#9]
1. 类似这个的编辑区域：https://bytemd.netlify.app/
2. 菜单栏的高度如何自定义呢，感觉有点大块头的样子

**Comment by imzbf** [comment]
> 1. 类似这个的编辑区域：https://bytemd.netlify.app/
> 2. 菜单栏的高度如何自定义呢，感觉有点大块头的样子

高亮编辑区不是这个编辑器的特色哦，目前没有这方面的计划。

关于菜单栏高度，这边的建议是通过自定义class，覆盖`md-toolbar`。

**Comment by lin-mt** [comment]
> > 1. 类似这个的编辑区域：https://bytemd.netlify.app/
> > 2. 菜单栏的高度如何自定义呢，感觉有点大块头的样子
> 
> 高亮编辑区不是这个编辑器的特色哦，目前没有这方面的计划。
> 
> 关于菜单栏高度，这边的建议是通过自定义class，覆盖`md-toolbar`。

好的吧～
