### ISSUE TITLE
Image resizing, position & border colour option when uploading the image

### ISSUE THREAD

**Issue by Udayendu** [imzbf/md-editor-rt#91]
### A great idea

This editor is really awesome and working perfectly. 
It would be nice to have few more features like:
  - image resizing
  - position the image with in the line like left, middle and right
  - add some border colour

**Comment by imzbf** [comment]
Thanks.

I will try some of these features. And they may serve as an extension.

But some of them cannot be adjusted, like 'add some border colour'. Because the style of the image is preset.

**Comment by Udayendu** [comment]
> Thanks.
> 
> I will try some of these features. And they may serve as an extension.
> 
> But some of them cannot be adjusted, like 'add some border colour'. Because the style of the image is preset.

Thank you @imzbf . Let me know when its ready, I can try and let you know.

**Comment by imzbf** [comment]
> > Thanks.
> > I will try some of these features. And they may serve as an extension.
> > But some of them cannot be adjusted, like 'add some border colour'. Because the style of the image is preset.
> 
> Thank you @imzbf . Let me know when its ready, I can try and let you know.

The plan is 

Insert `<img />` into the `markdown` content. Then modify its width and height. It may take a long time to establish an extension library. If you are in a hurry, try adding a similar tool item along with the [document](https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%90%A3%20NormalToolbar)

**Comment by Udayendu** [comment]
> > > Thanks.
> > > I will try some of these features. And they may serve as an extension.
> > > But some of them cannot be adjusted, like 'add some border colour'. Because the style of the image is preset.
> > 
> > 
> > Thank you @imzbf . Let me know when its ready, I can try and let you know.
> 
> The plan is
> 
> Insert `<img />` into the `markdown` content. Then modify its width and height. It may take a long time to establish an extension library. If you are in a hurry, try adding a similar tool item along with the [document](https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%90%A3%20NormalToolbar)

  Your thought process is exactly what I was looking for. So I am not in a hurry and prefer to wait to see how its coming up.

**Comment by ajboni** [comment]
This would be really useful! 

The way cherry-markdown implements this is quite nice, with the handlers on the preview pane:

https://tencent.github.io/cherry-markdown/examples/img.html

**Comment by imzbf** [comment]
> Insert `<img />` into the `markdown` content. Then modify its width and height. It may take a long time to establish an extension library. If you are in a hurry, try adding a similar tool item along with the [document](https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%90%A3%20NormalToolbar)

I added this component to . Usage: https://github.com/imzbf/md-editor-extension/blob/main/packages/rt/components/OriginalImg/README.md

**Comment by imzbf** [comment]
> This would be really useful!
> 
> The way cherry-markdown implements this is quite nice, with the handlers on the preview pane:
> 
> https://tencent.github.io/cherry-markdown/examples/img.html

Sorry, this looks well, but I don't have time to handle it

**Comment by Udayendu** [comment]
Hi @imzbf ,

I tried applying the image resize feature as you have suggested, but seems like the `defToolbars` parameter is not having any effect in the system.

Along with that I also tried to implement the mark and emoji, but they are also not working. Here is the code I am using:

```
import { MdEditor, config } from "md-editor-rt";
import "md-editor-rt/lib/style.css";
import { OriginalImg } from "@vavt/rt-extension";
import { Emoji } from "@vavt/rt-extension";
import { Mark } from "@vavt/rt-extension";
import MarkExtension from "markdown-it-mark";

config({
    markdownItConfig(md) {
      md.use(MarkExtension);
    },
  });

<MdEditor
            theme="light"
            language="en-US"
            previewTheme="github"
            noHighlight="true"
            modelValue={content}
            onChange={(modelValue) => {
              handleContent(modelValue);
            }}
            toolbars={[
              "bold",
              "underline",
              "italic",
              "strikeThrough",
              "-",
              "title",
              "sub",
              "sup",
              "quote",
              "unorderedList",
              "orderedList",
              "task",
              "-",
              "codeRow",
              "code",
              "link",
              "image",
              "table",
              "mermaid",
              "katex",
              "-",
              "revoke",
              "next",
              "save",
              "=",
              "prettier",
              "pageFullscreen",
              "fullscreen",
              "preview",
              "htmlPreview",
              "catalog",
              "github",
            ]}
            toolbarsExclude={["htmlPreview", "catalog", "github"]}
            scrollAuto="true"
            autoDetectCode="true"
            defToolbars={[
              <OriginalImg
                key="OriginalImg"
                trigger={<span>imgresize</span>}
                title="imgresize"
              />,
              <Mark key="Mark" trigger={<span>mark</span>} title="mark" />,
              <Emoji key="Emoji" trigger={<span>emoji</span>} title="emoji" />,
            ]}
          />
```

I can only see the following:

![image](https://github.com/imzbf/md-editor-rt/assets/1809177/acdfc7d9-e76f-46ca-a1b6-35e4736aa17b)

I have the following packages installed in the system:

```
"@vavt/rt-extension": "^1.0.2",
"markdown-it-mark": "^3.0.1",
"md-editor-rt": "^4.7.0",
```

Could you please let me why the other entries are not visible ?

**Comment by imzbf** [comment]
> Hi @imzbf ,
> 
> I tried applying the image resize feature as you have suggested, but seems like the `defToolbars` parameter is not having any effect in the system.
> 
> Along with that I also tried to implement the mark and emoji, but they are also not working. Here is the code I am using:
> 
> ```
> import { MdEditor, config } from "md-editor-rt";
> import "md-editor-rt/lib/style.css";
> import { OriginalImg } from "@vavt/rt-extension";
> import { Emoji } from "@vavt/rt-extension";
> import { Mark } from "@vavt/rt-extension";
> import MarkExtension from "markdown-it-mark";
> 
> config({
>     markdownItConfig(md) {
>       md.use(MarkExtension);
>     },
>   });
> 
> <MdEditor
>             theme="light"
>             language="en-US"
>             previewTheme="github"
>             noHighlight="true"
>             modelValue={content}
>             onChange={(modelValue) => {
>               handleContent(modelValue);
>             }}
>             toolbars={[
>               "bold",
>               "underline",
>               "italic",
>               "strikeThrough",
>               "-",
>               "title",
>               "sub",
>               "sup",
>               "quote",
>               "unorderedList",
>               "orderedList",
>               "task",
>               "-",
>               "codeRow",
>               "code",
>               "link",
>               "image",
>               "table",
>               "mermaid",
>               "katex",
>               "-",
>               "revoke",
>               "next",
>               "save",
>               "=",
>               "prettier",
>               "pageFullscreen",
>               "fullscreen",
>               "preview",
>               "htmlPreview",
>               "catalog",
>               "github",
>             ]}
>             toolbarsExclude={["htmlPreview", "catalog", "github"]}
>             scrollAuto="true"
>             autoDetectCode="true"
>             defToolbars={[
>               <OriginalImg
>                 key="OriginalImg"
>                 trigger={<span>imgresize</span>}
>                 title="imgresize"
>               />,
>               <Mark key="Mark" trigger={<span>mark</span>} title="mark" />,
>               <Emoji key="Emoji" trigger={<span>emoji</span>} title="emoji" />,
>             ]}
>           />
> ```
> 
> I can only see the following:
> 
> ![image](https://user-images.githubusercontent.com/1809177/271832215-acdfc7d9-e76f-46ca-a1b6-35e4736aa17b.png)
> 
> I have the following packages installed in the system:
> 
> ```
> "@vavt/rt-extension": "^1.0.2",
> "markdown-it-mark": "^3.0.1",
> "md-editor-rt": "^4.7.0",
> ```
> 
> Could you please let me why the other entries are not visible ?

Set `toolbars` to `['bold', 0, 1, 2, '=','github']`

**Comment by Udayendu** [comment]
@imzbf 
after adding 0, 1 and 2, the toolbar is looking like below:
![image](https://github.com/imzbf/md-editor-rt/assets/1809177/177db95d-e88e-4809-9e9b-71f7367baf1b)

Its not showing the logo. Just showing the text and the emoji are also not working. Here is the new entry for the MdEditor:
```
          <MdEditor
            theme="light"
            language="en-US"
            previewTheme="github"
            noHighlight="true"
            modelValue={content}
            onChange={(modelValue) => {
              handleContent(modelValue);
            }}
            toolbars={[
              "bold",
              "underline",
              "italic",
              "strikeThrough",
              "-",
              "title",
              "sub",
              "sup",
              "quote",
              "unorderedList",
              "orderedList",
              "task",
              "-",
              "codeRow",
              "code",
              "link",
              "image",
              "table",
              "mermaid",
              "katex",
              "0",
              "1",
              "2",
              "-",
              "revoke",
              "next",
              "save",
              "=",
              "prettier",
              "pageFullscreen",
              "fullscreen",
              "preview",
              "htmlPreview",
              "catalog",
              "github",
            ]}
            toolbarsExclude={["htmlPreview", "catalog", "github"]}
            scrollAuto="true"
            autoDetectCode="true"
            defToolbars={[
              <OriginalImg
                key="OriginalImg"
                trigger={<span>imgresize</span>}
                title="imgresize"
              />,
              <Mark key="Mark" trigger={<span>mark</span>} title="mark" />,
              <Emoji key="Emoji" trigger={<span>emoji</span>} title="emoji" />,
            ]}
          />
```

Let me know what am I missing because of which the icons are not available.

**Comment by imzbf** [comment]
This is normal, because the component requires icon. I usually look for the icons I need here: https://www.iconfont.cn/

Import them and replace `trigger` with iconfont.

**Comment by Udayendu** [comment]
> This is normal, because the component requires icon. I usually look for the icons I need here: https://www.iconfont.cn/
> 
> Import them and replace `trigger` with iconfont.

Thanks for the update. Have you released this features or they are in preview ?
If released, why they are not getting configured along with the default toolbar.

**Comment by imzbf** [comment]
> > This is normal, because the component requires icon. I usually look for the icons I need here: https://www.iconfont.cn/
> > Import them and replace `trigger` with iconfont.
> 
> Thanks for the update. Have you released this features or they are in preview ? If released, why they are not getting configured along with the default toolbar.

I don't understand，features are components? or iconfont?

**Comment by Udayendu** [comment]
> > > This is normal, because the component requires icon. I usually look for the icons I need here: https://www.iconfont.cn/
> > > Import them and replace `trigger` with iconfont.
> > 
> > 
> > Thanks for the update. Have you released this features or they are in preview ? If released, why they are not getting configured along with the default toolbar.
> 
> I don't understand，release components? or iconfont?

So, right now if we need these features then we have to enable them one by one. But as they are working well, add them to the default toolbar list and also include the iconfont. So that we dont need to configure them manually.

And same is for the export as PDF feature. We should include that too. I have not tested that yet, but from the github site what I can see that its a nice plugin to have.

**Comment by imzbf** [comment]
> So, right now if we need these features then we have to enable them one by one. But as they are working well, add them to the default toolbar list and also include the iconfont. So that we dont need to configure them manually.
> 
> And same is for the export as PDF feature. We should include that too. I have not tested that yet, but from the github site what I can see that its a nice plugin to have.

OK, I will provide default trigger node in the next version, so that we can use them directly

**Comment by Udayendu** [comment]
> > So, right now if we need these features then we have to enable them one by one. But as they are working well, add them to the default toolbar list and also include the iconfont. So that we dont need to configure them manually.
> > And same is for the export as PDF feature. We should include that too. I have not tested that yet, but from the github site what I can see that its a nice plugin to have.
> 
> OK, I will provide default trigger node in the next version, so that we can use them directly

Thank you. We already have a **toolbarsExclude** list where people can add the item they don't need in their toolbar. Hence I thought, adding them to the default list would be a better option. Kindly include the PDF exporter to the list as well.

Let me know if you want me to file a RFE for this request as this issue has already been closed.

**Comment by imzbf** [comment]
> Thank you. We already have a **toolbarsExclude** list where people can add the item they don't need in their toolbar. Hence I thought, adding them to the default list would be a better option. Kindly include the PDF exporter to the list as well.
> 
> Let me know if you want me to file a RFE for this request as this issue has already been closed.


Sorry, not very recommended to do this. 

Because component `ExportPDF` has some large dependencies. 

Once used as default, there will be a lot of extra code in the projects of partners who do not need this feature. Because components in `toolbarsExclude` cannot be referenced on demand

**Comment by Udayendu** [comment]
> > Hi @imzbf ,
> > I tried applying the image resize feature as you have suggested, but seems like the `defToolbars` parameter is not having any effect in the system.
> > Along with that I also tried to implement the mark and emoji, but they are also not working. Here is the code I am using:
> > ```
> > import { MdEditor, config } from "md-editor-rt";
> > import "md-editor-rt/lib/style.css";
> > import { OriginalImg } from "@vavt/rt-extension";
> > import { Emoji } from "@vavt/rt-extension";
> > import { Mark } from "@vavt/rt-extension";
> > import MarkExtension from "markdown-it-mark";
> > 
> > config({
> >     markdownItConfig(md) {
> >       md.use(MarkExtension);
> >     },
> >   });
> > 
> > <MdEditor
> >             theme="light"
> >             language="en-US"
> >             previewTheme="github"
> >             noHighlight="true"
> >             modelValue={content}
> >             onChange={(modelValue) => {
> >               handleContent(modelValue);
> >             }}
> >             toolbars={[
> >               "bold",
> >               "underline",
> >               "italic",
> >               "strikeThrough",
> >               "-",
> >               "title",
> >               "sub",
> >               "sup",
> >               "quote",
> >               "unorderedList",
> >               "orderedList",
> >               "task",
> >               "-",
> >               "codeRow",
> >               "code",
> >               "link",
> >               "image",
> >               "table",
> >               "mermaid",
> >               "katex",
> >               "-",
> >               "revoke",
> >               "next",
> >               "save",
> >               "=",
> >               "prettier",
> >               "pageFullscreen",
> >               "fullscreen",
> >               "preview",
> >               "htmlPreview",
> >               "catalog",
> >               "github",
> >             ]}
> >             toolbarsExclude={["htmlPreview", "catalog", "github"]}
> >             scrollAuto="true"
> >             autoDetectCode="true"
> >             defToolbars={[
> >               <OriginalImg
> >                 key="OriginalImg"
> >                 trigger={<span>imgresize</span>}
> >                 title="imgresize"
> >               />,
> >               <Mark key="Mark" trigger={<span>mark</span>} title="mark" />,
> >               <Emoji key="Emoji" trigger={<span>emoji</span>} title="emoji" />,
> >             ]}
> >           />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I can only see the following:
> > ![image](https://user-images.githubusercontent.com/1809177/271832215-acdfc7d9-e76f-46ca-a1b6-35e4736aa17b.png)
> > I have the following packages installed in the system:
> > ```
> > "@vavt/rt-extension": "^1.0.2",
> > "markdown-it-mark": "^3.0.1",
> > "md-editor-rt": "^4.7.0",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you please let me why the other entries are not visible ?
> 
> Set `toolbars` to `['bold', 0, 1, 2, '=','github']`

Hi @imzbf, I have implemented the image resize option and realised that only width option is available. No parameter for height. Its missing or intentional ?? Because image size should be the combination of height and width via the image tag.

**Comment by imzbf** [comment]
https://github.com/imzbf/md-editor-rt/issues/91#issuecomment-1794917471

@Udayendu Udayend

Intentional. Because in most cases, height is adaptive to the width. If it's necessary, you can also proactively add
