### ISSUE TITLE
i want to add support for indonesian language

### ISSUE THREAD

**Issue by vallerydelexy** [imzbf/md-editor-rt#92]
### A great idea

i want to add support for indonesian language, where are the strings i should translate?

edit: nevermind, i found them https://github.com/imzbf/md-editor-rt/blob/develop/packages/MdEditor/config.ts

**Comment by imzbf** [comment]
Sorry, Please submit it to [md-editor-extension](https://github.com/imzbf/md-editor-extension). 

Because the editor has two versions. And we can imoport it here as needed.

**Comment by imzbf** [comment]
Thank you for your participation, please refer to the [example here](https://github.com/imzbf/md-editor-extension#language)，It is very simple
