### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by vallerydelexy** [imzbf/md-editor-rt#96]
### Describe the issue

using md-editor-rt@4.2.2 on a next@13.4.12 project with the new app router
the editor still works good, but theres a warning on terminal.

The module Editor.cjs inside md-editor-rt is requesting a dependency.
This dependency request is an expression, which is not recommended due to the potential for runtime issues.

consider modifying the import statements to use static strings instead of expressions.
```
- warn ./node_modules/.pnpm/md-editor-rt@4.2.2_@codemirror+state@6.2.1_@codemirror+view@6.15.3_@lezer+common@1.0.3_react-dom@18.2.0_react@18.2.0/node_modules/md-editor-rt/lib/cjs/chunks/Editor.cjs
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/.pnpm/md-editor-rt@4.2.2_@codemirror+state@6.2.1_@codemirror+view@6.15.3_@lezer+common@1.0.3_react-dom@18.2.0_react@18.2.0/node_modules/md-editor-rt/lib/cjs/chunks/Editor.cjs
./node_modules/.pnpm/md-editor-rt@4.2.2_@codemirror+state@6.2.1_@codemirror+view@6.15.3_@lezer+common@1.0.3_react-dom@18.2.0_react@18.2.0/node_modules/md-editor-rt/lib/cjs/index.cjs
./components/TextArea.js
./app/dashboard/newpost/page.js
```

### Procedure version

md-editor-rt@4.2.2, nodejs@18.15.0, next@13.4.12

**Comment by imzbf** [comment]
Here is a solution

https://github.com/i18next/next-i18next/issues/1545#issuecomment-1005990731

**Comment by vallerydelexy** [comment]
It works, but it seems to be more a workaround than a solution. It would be great to really fix the import statement

**Comment by imzbf** [comment]
> It works, but it seems to be more a workaround than a solution. It would be great to really fix the import statement..
> 
> here is my `next.config.js`
> 
> ```
> module.exports = {
>   swcMinify: true,
>   reactStrictMode: true,
>   images: {
>     domains: ['res.cloudinary.com']
>   },
>   webpack: (config, { isServer }) => {
>     if (!isServer) {
>       config.resolve = {
>         ...config.resolve,
>         fallback: {
>           ...config.resolve.fallback,
>         },
>       };
>     }
>     config.module = {
>       ...config.module,
>       exprContextCritical: false,
>     };
>     return config;
>   },
> }
> ```

I have searched for documents related to `nextjs`.

There is no way to handle this: 

```js
import('https://xxx.com/xxx.lib').then(() => {})
```

In project used `webpack` or `vite`. I have added [relevant annotation](https://github.com/imzbf/md-editor-rt/blob/develop/packages/MdEditor/layouts/Content/hooks/useMermaid.ts#L61) to cancel compilation

**Comment by Nomango** [comment]
Same issue

**Comment by imzbf** [comment]
> Same issue. I encountered this problem for the first time using it, which made me a little worried.

issue still exists, even if configured as above?

**Comment by Nomango** [comment]
> > Same issue. I encountered this problem for the first time using it, which made me a little worried.
> 
> issue still exists, even if configured as above?

I don't try to suppress this error. Just use `marked` instead.
