### ISSUE TITLE
How to change language to English?

### ISSUE THREAD

**Issue by KarteekAti** [imzbf/md-editor-rt#97]
### Describe the issue

I want the highlighting text to be in English, how can i change the language

### Procedure version

main

**Comment by imzbf** [comment]
this parameter: https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%94%A4%20language

**Comment by KarteekAti** [comment]
> this parameter: https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%94%A4%20language

Thank you
