### ISSUE TITLE
When a duplicate occurs in the outline, the key is duplicated.

### ISSUE THREAD

**Issue by Edric-Li** [imzbf/md-editor-rt#98]
### 描述这个Bug

![image](https://github.com/imzbf/md-editor-rt/assets/50992790/1b10ae2d-163d-4ac6-8d11-33d32b552c77)
![image](https://github.com/imzbf/md-editor-rt/assets/50992790/7d7aeb7a-58c1-4489-b5cc-015a6064635c)

### 版本号

latest

**Comment by imzbf** [comment]
Define different id for `heading`: https://imzbf.github.io/md-editor-rt/en-US/docs#%F0%9F%8E%B1%20mdHeadingId

**Comment by Edric-Li** [comment]
@imzbf 
I tried your solution, but it didn't work.
I use it like this.
![image](https://github.com/imzbf/md-editor-rt/assets/50992790/25e97044-dd06-44c1-bd81-579744694792)
generateUniqueKey method, I'm guaranteed to return a unique value. But the browser still reports an error.

**Comment by Edric-Li** [comment]
![image](https://github.com/imzbf/md-editor-rt/assets/50992790/7f1a48e4-bb32-468b-ac8c-bed63e50616c)

**Comment by Edric-Li** [comment]
[README.cn.md](https://github.com/imzbf/md-editor-rt/files/12334168/README.cn.md)
Here is my md file.

**Comment by imzbf** [comment]
I fixed this in `beta`, have a try in this way:

```shell
yarn add md-editor-rt@beta
```

**Comment by Edric-Li** [comment]
> I fixed this in `beta`, have a try in this way:
> 
> ```shell
> yarn add md-editor-rt@beta
> ```
I tried it, and the bug has been fixed. May I ask when will the official version be released?

**Comment by imzbf** [comment]
It may take two weeks, but there are still no solutions to a special bug

**Comment by xiaoxing92** [comment]
In next13 router mode, the client component is used in the server component and const scrollElement=document. documentElement is declared; It will result in server rendering failure, SSR failure, no need for document.documentElement, and MdCatalog component inability to anchor

**Comment by imzbf** [comment]
> In next13 router mode, the client component is used in the server component and const scrollElement=document. documentElement is declared; It will result in server rendering failure, SSR failure, no need for document.documentElement, and MdCatalog component inability to anchor

another way to set this attr: https://github.com/imzbf/md-editor-rt/issues/101#issuecomment-1685222297

**Comment by imzbf** [comment]
latest version had been published
