### ISSUE TITLE
previewOnly 属性怎么不存在了

### ISSUE THREAD

**Issue by imyuanli** [imzbf/md-editor-rt#99]
### Describe the issue

4.0版本以后为什么不支持 previewOnly了

### Procedure version

^4.2.1

**Comment by imzbf** [comment]
改成独立的组件了，https://imzbf.github.io/md-editor-rt/en-US/contrast#%F0%9F%AA%A4%20%E5%86%85%E9%83%A8%E7%BB%84%E4%BB%B6
